const questionPool = [{id:	1	,question:"	腸内細菌科細菌はどれか。2つ選べ。	",	level:	1	,choices:["	<i>Acinetobacter baumannii</i>	","	<i>Escherichia coli</i>	","	<i>Klebsiella pneumoniae</i>	","	<i>Pseudomonas aeruginosa</i>	","	<i>Enterococcus faecium</i>	"],	correct:[		"b",	"c",			],explanation:"	腸内細菌目（<em>Enterobacterales</em>）は細菌分類上の「目（Order）」にあたり、腸内細菌科（<em>Enterobacteriaceae</em>）を含む複数の科を内包する分類単位である。一方、腸内細菌科（<em>Enterobacteriaceae</em>）は腸内細菌目に属する「科（Family）」であり、<em>Escherichia</em>（大腸菌）や<em>Klebsiella</em>（肺炎桿菌）などの属（Genus）を含む。また、「腸内細菌（gut microbiota）」とは腸内に生息する細菌全般を指す言葉であり、分類学的な定義を持たないが、腸内細菌科に属する細菌をはじめ、腸内に共生する多様な微生物を包含している。      	",	selectionCount:	2	},		
{id:	2	,question:"	グラム陰性ブドウ糖非発酵菌はどれか。2つ選べ。	",	level:	1	,choices:["	<i>Acinetobacter baumannii</i>	","	<i>Escherichia coli</i>	","	<i>Klebsiella pneumoniae</i>	","	<i>Pseudomonas aeruginosa</i>	","	<i>Staphylococcus aureus</i>	"],	correct:[	"a",			"d",		],explanation:"	グラム陰性桿菌は、臨床的にはインフルエンザ菌のような小桿菌、大腸菌をはじめとする腸内細菌目細菌、緑膿菌をはじめとするブドウ糖非発酵菌（non-fermenting bacteria）に大別すると理解しやすい。ブドウ糖の発酵、非発酵は異化過程（エネルギー獲得）の相違による。大腸菌などの腸内細菌目細菌は、発酵と呼吸の双方によってエネルギーを獲得するため、嫌気・好気の両方で発育が可能であり、通性嫌気性菌とも呼ばれる。一方、緑膿菌などのブドウ糖非発酵菌は、ブドウ糖を発酵できず、もっぱら呼吸によってのみエネルギーを獲得するため、偏性好気性菌とも呼ばれる。ただし、緑膿菌は嫌気呼吸という脱窒によってもエネルギーを獲得することができる。ブドウ糖非発酵菌の多くが土壌、水、植物、動物などの自然環境中に広く存在している。	",	selectionCount:	2	},		
{id:	3	,question:"	偏性嫌気性菌はどれか。2つ選べ。	",	level:	1	,choices:["	<i>Bacillus anthracis</i>	","	<i>Bacteroides fragilis</i>	","	<i>Campylobacter jejuni </i>	","	<i>Clostridium perfringens</i>	","	<i>Corynebacterium diphtheria</i>	"],	correct:[		"b",		"d",		],explanation:"	偏性嫌気性菌（Obligate anaerobes）は酸素存在下で増殖ができず、場合によっては酸素により死滅する特性を持つ細菌である。単に嫌気性菌とも呼ばれるが、通性嫌気性菌との相違を明確にする場合には偏性嫌気性菌と呼ばれる。これらの細菌は酸素を利用しない代謝経路（嫌気性呼吸や発酵）によってエネルギーを産生する。口腔内や腸内の常在菌の多くは、偏性嫌気性菌である。<em>Bacteroides</em>属や<em>Clostridium</em>属のほかに、<em>Peptococcus</em>属や<em>Fusobacterium</em>属などがよく知られている。	",	selectionCount:	2	},		
{id:	4	,question:"	偏性細胞内増殖性の細菌菌はどれか。2つ選べ。	",	level:	1	,choices:["	<i>Acinetobacter baumannii</i>	","	<i>Chlamydia trachomatis</i>	","	<i>Haemophilus influenzae</i>	","	<i>Mycoplasma pneumoniae</i>	","	<i>Rickettsia rickettsii</i>	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	5	,question:"	「薬剤耐性（AMR）対策アクションプラン（2023-2027）」において、使用量減が目標として定めれられている経口抗菌薬はどれか。2 つ選べ。	",	level:	3	,choices:["	セファロスポリン系薬	","	マクロライド系薬	","	ペニシリン系薬	","	テトラサイクリン系薬	","	アミノグリコシド系薬	"],	correct:[	"a",	"b",				],explanation:"	<a href='http://filgap.kenkyuukai.jp/special/?id=42276' target='_blank'>使用量減が目標として定められている経口抗菌薬</a>	",	selectionCount:	2	},		
{id:	6	,question:"	WHOが定めるAWaRe分類のAccessに含まれる抗菌薬はどれか。2 つ選べ。	",	level:	3	,choices:["	コリスチン	","	アンピシリン	","	アモキシシリン	","	レボフロキサシン	","	メロペネム	"],	correct:[		"b",	"c",			],explanation:"	<a href='http://filgap.kenkyuukai.jp/special/?id=43178' target='_blank'>AWaRe分類</a>	",	selectionCount:	2	},		
{id:	7	,question:"	接触予防策が必要な病原体はどれか。2つ選べ。	",	level:	2	,choices:["	<i>Streptococcus pneumoniae</i>	","	<i>Bacillus cereus</i>	","	<i>Clostridioides difficile</i>	","	<i>Haemophilus influenzae</i>	","	methicillin-resistant<i>Staphylococcus aureus</i>	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	8	,question:"	緑膿菌の特徴として正しいのはどれか。2つ選べ。	",	level:	2	,choices:["	栄養要求性が高く培養が難しい。	","	流しなどの水回りからよく分離される。	","	病原性が高く健常者にも容易に感染する。	","	あらゆるペニシリン系薬に自然耐性を示す。	","	人工呼吸器関連肺炎の主要な原因菌の一つである。	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	9	,question:"	Therapeutic drug monitoring（TDM）が必要な抗菌薬はどれか。2つ選べ。	",	level:	3	,choices:["	アジスロマイシン	","	アモキシシリン	","	アルベカシン	","	バンコマイシン	","	レボフロキサシン	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	10	,question:"	細胞壁の合成を阻害する抗菌薬はどれか。2つ選べ。	",	level:	2	,choices:["	アミノグリコシド系薬	","	グリコペプチド系薬	","	フルオロキノロン系薬	","	β-ラクタム系薬	","	マクロライド系薬	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	11	,question:"	β溶血性を示す細菌はどれか。2つ選べ。	",	level:	3	,choices:["	<i>Streptococcus mitis</i>	","	<i>Streptococcus mutans</i>	","	<i>Streptococcus pyogenes</i>	","	<i>Streptococcus pneumoniae</i>	","	<i>Streptococcus dysgalactiae</i> subsp. <i>equisimilis</i>	"],	correct:[			"c",		"e",	],explanation:"	2024本試験-<strong>問題3</strong> 類題	",	selectionCount:	2	},		
{id:	12	,question:"	コアグラーゼ陽性のブドウ球菌はどれか。2つ選べ。	",	level:	3	,choices:["	<i>Staphylococcus aureus</i>	","	<i>Staphylococcus intermedius</i>	","	<i>Staphylococcus epidermidis</i>	","	<i>Staphylococcus lugdunensis</i>	","	<i>Staphylococcus saprophyticus</i>	"],	correct:[	"a",	"b",				],explanation:"	2024本試験-<strong>問題4</strong> 類題	",	selectionCount:	2	},		
{id:	13	,question:"	新生児の髄膜炎の原因菌として最も考慮すべき細菌はどれか。2つ選べ。	",	level:	3	,choices:["	<i>Escherichia coli</i>	","	<i>Staphylococcus aureus</i>	","	<i>Pseudomonas aeruginosa</i>	","	<i>Streptococcus agalactiae</i>	","	<i>Streptococcus pneumoniae</i>	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	14	,question:"	急性単純性膀胱炎の原因菌と第一選択薬の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	<i>Escherichia coli</i>　---　セファクロル	","	<i>Klebsiella pneumoniae</i>　---　コリスチン	","	<i>Enterococcus faecium</i>　---　セファゾリン	","	<i>Pseudomonas aeruginosa</i>　---　セフトリアキソン	","	<i>Staphylococcus saprophyticus</i>　---　レボフロキサシン	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	15	,question:"	ステルス型カルバペネマーゼ産生腸内細菌目細菌（CPE）が保有するβ-ラクタマーゼはどれか。	",	level:	4	,choices:["	KPC1	","	TEM1	","	IMP-6	","	NDM-1	","	CTX-M-1	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	16	,question:"	<em>Clostridioides difficile</em>に有効な抗菌薬はどれか。2つ選べ。	",	level:	3	,choices:["	メロペネム	","	バンコマイシン	","	クリンダマイシン	","	アジスロマイシン	","	フィダキソマイシン	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	17	,question:"	β-ラクタマーゼ非産生アンピシリン耐性インフルエンザ菌（BLNAR）に有効な抗菌薬はどれか。2つ選べ。	",	level:	3	,choices:["	テジゾリド	","	レボフロキサシン	","	トシル酸スルタミシリン	","	タゾバクタム/ピペラシリン	","	アモキシシリン/クラブラン酸	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	18	,question:"	β-ラクタマーゼ産生アモキシシリン/クラブラン酸耐性インフルエンザ菌（BLPACR）の耐性因子として正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	<em>ftsI</em>の変異	","	TEM型β-ラクタマーゼ	","	CTX-M型β-ラクタマーゼ	","	<em>mecA</em>遺伝子の獲得	","	 <em>mcr1</em>遺伝子の獲得	"],	correct:[						],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	19	,question:"	メタロβ-ラクタマーゼについて正しいのはどれか。2つ選べ。	",	level:	5	,choices:["	ボロン酸で阻害される。	","	Ambler分類のclass Bに属する。	","	NDM-1型は腸内細菌目のみが保有する。	","	緑膿菌が元来保有している耐性因子である。	","	IMP-6産生大腸菌はしばしばカルバペネム系薬に感受性を示す。	"],	correct:[		"b",			"e",	],explanation:"	IMP-6はステルス型としても知られており、しばしばカルバペネム系薬に感受性を示す。しかしながら、基準変更によって選択肢は変わりうるので注意が必要。	",	selectionCount:	2	},		
{id:	20	,question:"	デエスカレーションに相当するのはどれか。2 つ選べ。	",	level:	3	,choices:["	メロペネムからセフタジジムに変更する。	","	アンピシリンからセファゾリンに変更する。	","	バンコマイシンからセファゾリンに変更する。	","	アルベカシンからダプトマイシンに変更する。	","	セフトリアキソンからセフタジジムに変更する。	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	21	,question:"	エスカレーションに相当するのはどれか。2つ選べ。	",	level:	3	,choices:["	メロペネム1回0.5gから1回1gに増量する。	","	メロペネム1日2回から1日4回に増量する。	","	セフトリアキソンからメロペネムに変更する。	","	アモキシシリンからセフトリアキソンに変更する。	","	注射用シプロフロキサシンから内服のレボフロキサシンに切り替える。	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	22	,question:"	核酸増幅法はどれか。2つ選べ。	",	level:	2	,choices:["	PCR	","	RIA	","	LAMP	","	TPHA	","	ELISA	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	23	,question:"	IGRAに用いられている結核特異的抗原はどれか。2つ選べ。	",	level:	4	,choices:["	KatG	","	MDP1	","	Ag85B	","	CFP-10	","	ESAT-6	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	24	,question:"	qSOFAに用いられる項目はどれか。2つ選べ。	",	level:	2	,choices:["	血圧	","	脈拍	","	呼吸数	","	SpO<sub>2</sub>	","	白血球数	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	25	,question:"	eGFRの算出に必要な項目はどれか。2つ選べ。	",	level:	2	,choices:["	BUN	","	Na	","	Cr	","	年齢	","	体重	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	26	,question:"	Child-Pugh分類に必要な項目はどれか。2つ選べ。	",	level:	3	,choices:["	BUN	","	GOT（AST）	","	GPT（ALT）	","	アルブミン	","	ビリルビン	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	27	,question:"	キノロン耐性に関連する遺伝子はどれか。2つ選べ。	",	level:	4	,choices:["	<em>gyrA</em>	","	<em>parC</em>	","	<em>mcr1</em>	","	<em>vanA</em>	","	<em>bla</em><sub>IMP</sub>	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	28	,question:"	経口第三世代セファロスポリン系薬はどれか。2つ選べ。	",	level:	2	,choices:["	セフジニル	","	セファクロル	","	セフタジジム	","	セフトリアキソン	","	セフジトレン-ピボキシル	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	29	,question:"	マクロライド系薬はどれか。2つ選べ。	",	level:	2	,choices:["	アジスロマイシン	","	クラリスロマイシン	","	ゲンタマイシン	","	テジゾリド	","	ミノサイクリン	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	30	,question:"	内服できない抗菌薬はどれか。2つ選べ。	",	level:	2	,choices:["	アルベカシン	","	セファクロル	","	テイコプラニン	","	テジゾリド	","	リネゾリド	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	31	,question:"	抗MRSA薬について、正しいのはどれか 。 2 つ選べ。	",	level:	3	,choices:["	テジゾリドは内服が可能である。	","	アルベカシンはバイオアベイラビリティが高い。	","	リネゾリドは肺サーファクタントにより不活化される。	","	ダプトマイシン投与中は骨髄抑制に注意が必要である。	","	グリコペプチド系薬のTDMでは、トラフの測定が有用である。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	32	,question:"	バンコマイシンについて正しいのはどれか。2 つ選べ。	",	level:	4	,choices:["	バイオアベイラビリティが高い。	","	TDMではピークの測定が必須である。	","	副作用としてred man症候群が知られている。	","	D-Ala-D-Alaに結合し、細胞壁の合成を阻害する。	","	メチシリン感受性黄色ブドウ球菌（MSSA）に対しては無効である。	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	33	,question:"	バンコマイシン耐性腸球菌（VRE）について正しいのはどれか。2つ選べ。	",	level:	5	,choices:["	芽胞形成菌である。	","	セファゾリンが有効である。	","	バンコマイシン耐性はPBPの変異によるものである。	","	VREによる感染症は、感染症法の5類全数報告の対象である。	","	<em>Enterococcus faecalis</em>よりも<em>Enterococcus faecium</em>の方が耐性化傾向にある。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	34	,question:"	抗菌薬に関する以下の説明に関して正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	広域抗菌薬にはアンピシリンが含まれる。	","	コリスチンはグラム陽性菌に無効である。	","	メトロニダゾールは嫌気性菌に無効である。	","	セファロスポリン系薬は腸球菌に無効である。	","	フィダキソマイシンは抗MRSA薬の一つである。	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	35	,question:"	検査に関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	喀痰の採取は日中が望ましい。	","	喀痰の採取直前にうがいがすることが望ましい。	","	百日咳菌の培養にはボルデ・ジャング培地が有用である。	","	淋菌・クラミジア感染症を疑う場合には中間尿を採取する。	","	抗体検査の方が、抗原検査（イムノクロマト法）よりも結果が早く判明する。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	36	,question:"	検査に関する説明として正しいのはどれか。2つ選べ。	",	level:	2	,choices:["	初尿とは出生後最初に採取した新生児の尿を指す。	","	中間尿は食後2時間以上経過した後に採取した尿を指す。	","	大腸菌による尿路感染症を疑う場合には中間尿を採取する。	","	抗体検査の方が、抗原検査（イムノクロマト法）よりも結果が早く判明する。	","	新生児早発型GBS感染予防対策のためのスクリーニング検査として、全妊婦に対してGBS培養検査が推奨されている。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	37	,question:"	結核の病理像の特徴として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	乾酪壊死	","	核内封入体	","	半月体形成	","	好中球の集簇	","	ラングハンス型巨細胞	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	38	,question:"	<em>Mycobacterium avium</em>による非結核性抗酸菌症に用いる抗菌薬として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	colistin	","	isoniazid	","	ethambutol	","	minocycline	","	clarithromycin	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	39	,question:"	日本で2010年よりも増加している薬剤耐性菌はどれか。2つ選べ。	",	level:	5	,choices:["	多剤耐性緑膿菌	","	キノロン耐性大腸菌	","	多剤耐性アシネトバクター	","	メチシリン耐性黄色ブドウ球菌	","	第三世代セファロスポリン耐性大腸菌	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	40	,question:"	5類感染症として全数を届け出る必要がある薬剤耐性菌感染症はどれか。2つ選べ。	",	level:	4	,choices:["	カルバペネム耐性腸内細菌目細菌感染症	","	基質特異性拡張型β-ラクタマーゼ産生大腸菌感染症	","	バンコマイシン耐性腸球菌感染症	","	β-ラクタマーゼ非産生アンピシリン耐性インフルエンザ菌感染症	","	ペニシリン耐性肺炎球菌感染症	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	41	,question:"	喀痰の検体として適しているのはどれか。2つ選べ。	",	level:	2	,choices:["	唾液，完全な粘液性痰	","	Geckler分類で1の検体	","	Geckler分類で5の検体	","	Miller-Jones分類でM1の検体	","	 Miller-Jones分類でP3の検体	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	42	,question:"	尿路感染症の主な原因菌はどれか。	",	level:	1	,choices:["	<em>Escherichia coli</em>	","	<em>Bacteroides fragilis</em>	","	<em>Staphylococcus aureus</em>	","	<em>Streptococcus agalactiae</em>	","	<em>Pseudomonas aeruginosa</em>	"],	correct:[	"a",					],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	43	,question:"	グラム染色による分類に関して正しい説明はどれか。2つ選べ。	",	level:	1	,choices:["	グラム陽性菌は外膜を持たない。	","	グラム陽性菌は鞭毛を持たない。	","	グラム陽性菌はO抗原を持たない。	","	グラム陰性菌はK抗原を持たない。	","	グラム陰性菌は排出ポンプを持たない。	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	44	,question:"	細菌に関する説明として正しいのはどれか。2つ選べ。	",	level:	2	,choices:["	<em>Salmonella</em> Typhiは鞭毛を持たない。	","	<em>Shigella sonnei</em>はシガ毒素を産生しない。	","	<em>Acinetobacter baumannii</em>は鞭毛を持たない。	","	<em>Corynebacterium diphtheriae</em>は芽胞を形成する。	","	<em>Neisseria meningitidis</em>は厚い莢膜を有し、乾燥に強い。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	45	,question:"	急性中耳炎の主な原因菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Escherichia coli</em>	","	<em>Enterococcus faecium</em>	","	<em>Staphylococcus aureus</em>	","	<em>Haemophilus influenzae</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	46	,question:"	菌血症の主な原因菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Escherichia coli</em>	","	<em>Enterococcus faecium</em>	","	<em>Staphylococcus aureus</em>	","	<em>Haemophilus influenzae</em>	","	<em>Streptococcus agalactiae</em>	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	47	,question:"	ワクチンで予防可能な感染症はどれか。2つ選べ。	",	level:	2	,choices:["	ガス壊疽	","	侵襲性髄膜炎菌感染症	","	侵襲性肺炎球菌感染症	","	多剤耐性緑膿菌感染症	","	侵襲性肺アスペルギルス症	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	48	,question:"	空気予防策が必要な感染症はどれか。2つ選べ。	",	level:	1	,choices:["	結核	","	風疹	","	水痘	","	ジフテリア	","	インフルエンザ	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	49	,question:"	基質特異性拡張型β-ラクタマーゼによって分解される抗菌薬はどれか。2つ選べ。	",	level:	4	,choices:["	アンピシリン	","	セフトリアキソン	","	セフメタゾール	","	ファロペネム	","	メロペネム	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	50	,question:"	CTX-M型β-ラクタマーゼの主要な産生菌はどれか。2つ選べ。	",	level:	5	,choices:["	<em>Escherichia coli</em>	","	<em>Enterococcus faecium</em>	","	<em>Staphylococcus aureus</em>	","	<em>Klebsiella pneumoniae</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	51	,question:"	β-ラクタマーゼについて正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	KPCはセリン型である。	","	IMP-6はメタロ型である。	","	OXA型はAmbler分類class Aに分類される。	","	CTX-M型はAmbler分類class Bに分類される。	","	メタロ型はセファマイシン系薬を分解できない。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	52	,question:"	コリスチンについて正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	静菌的な作用を示す。	","	主に肝臓で代謝される。	","	グラム陽性菌に有効である。	","	外膜のLPSが標的となっている。	","	伝達性の耐性遺伝子として<em>mcr1</em>が知られている。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	53	,question:"	バンコマイシンについて正しいのはどれか。2つ選べ。	",	level:	5	,choices:["	TDMではピークの測定が必要である。	","	黄色ブドウ球菌の10%が耐性を示す。	","	耐性機構として分解酵素が知られている。	","	耐性遺伝子の<em>vanA</em>は伝達性がある。	","	<em>Lactobacillus</em>属は一次耐性を示す。	"],	correct:[						],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	54	,question:"	肺炎球菌のマクロライド耐性遺伝子はどれか。2つ選べ。	",	level:	5	,choices:["	<em>ermB</em>	","	<em>ftsI</em>	","	<em>mcr1</em>	","	<em>mecA</em>	","	<em>mefA</em>	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	55	,question:"	β-ラクタム系薬について正しい説明はどれか。2つ選べ。	",	level:	4	,choices:["	Time above MICが有効性と関連する。	","	セフトリアキソンは半減期が長いので、1日1回の投与が推奨される。	","	セファロスポリン系薬のβ-ラクタム環に隣接するのは5員環である。	","	カルバペネム系薬のβ-ラクタム環に隣接する5員環には硫黄が含まれる。	","	ペニシリン系薬はβ-ラクタム環に隣接する5員環の1つが2重結合になっている。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	56	,question:"	フルオロキノロン系薬について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	非定型菌にも有効である。	","	Time above MICが有効性と関連する。	","	シプロフロキサシンの半減期は約12時間である。	","	結核は元来フルオロキノロン系薬に自然耐性を示す。	","	耐性変異しやすい遺伝子領域はQRDRとして知られている。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	57	,question:"	マクロライド系薬について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	細胞壁合成を阻害する。	","	非定型菌には無効である。	","	肺炎球菌の耐性は知られていない。	","	クラリスロマイシンは14員環である。	","	アジスロマイシンは半減期が長いので、3日間の内服で有効な組織内濃度が約7日間持続する。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	58	,question:"	<em>Campylobacter jejuni</em>/<em>coli</em>について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	芽胞を形成する。	","	らせん状の細菌である。	","	100℃でも殺菌されない。	","	鳥類の腸管内に常在する。	","	マクロライド系薬に自然耐性を示す。	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	59	,question:"	ディフィシル菌感染症の治療薬として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	ST合剤	","	ペンタミジン	","	バンコマイシン	","	メトロニダゾール	","	フィダキソマイシン	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	60	,question:"	腸管出血性大腸菌感染症について正しい説明はどれか。2つ選べ	",	level:	3	,choices:["	5類感染症に定められている。	","	ベロ毒素が病態に関与している。	","	溶血性尿毒症症候群の原因となる。	","	無症候であっても入院措置が必要である。	","	感染予防にはアルコール消毒が使用できない。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	61	,question:"	肺炎の原因菌で尿中抗原検査が診断に有用なのはどれか。2つ選べ。（第107回医師国家試験A14より一部改変）	",	level:	2	,choices:["	<em>Haemophilus influenzae</em>	","	<em>Legionella pneumophila</em>	","	<em>Mycoplasma pneumoniae</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	62	,question:"	生後2か月から開始可能なワクチンはどれか。2つ選べ。	",	level:	2	,choices:["	ヒブワクチン	","	MRワクチン	","	水痘ワクチン	","	日本脳炎ワクチン	","	小児用肺炎球菌ワクチン	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	63	,question:"	結核の発病リスクとなる状態はどれか。2つ選べ。	",	level:	2	,choices:["	BCG接種後である。	","	肺炎球菌ワクチン接種後である。	","	コントロール不良の糖尿病がある。	","	イソニアジドによる治療中である。	","	インフリキシマブ（抗TNFα抗体）による治療中である。	"],	correct:[						],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	64	,question:"	病原体とその培養に用いる培地の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	<em>Campylobacter jejuni</em>/<em>coli</em>　 ---　Skirrow培地	","	<em>Neisseria gonorrhoeae</em>　 ---　小川培地	","	<em>Haemophilus influenzae</em>　 ---　羊血液寒天培地	","	<em>Bordetella pertussis</em>　 ---　ボルデ-ジャング培地	","	<em>Chlamydia pneumoniae</em>　 ---　BCYE α培地	"],	correct:[						],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	65	,question:"	耐性菌とその原因遺伝子の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	5	,choices:["	キノロン耐性大腸菌　 ---　<em>gyrA</em>変異	","	コリスチン耐性アシネトバクター　 ---　 <em>ftsI</em>変異	","	β-ラクタマーゼ非産生アンピシリン耐性インフルエンザ菌　---　 <em>mcr1</em>	","	ペニシリン耐性肺炎球菌　 ---　<em>bla</em><sub>IMP</sub>	","	メチシリン耐性黄色ブドウ球菌　 ---　 <em>mecA</em>	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	66	,question:"	qSOFAの基準に含まれる項目はどれか。全て選べ。	",	level:	3	,choices:["	血圧	","	体温	","	脈拍	","	呼吸数	","	意識障害	"],	correct:[	"a",			"d",	"e",	],explanation:"	解説なし	",	selectionCount:	"all"	},		
{id:	67	,question:"	抗菌薬とその作用標的の組み合わせとして<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	アジスロマイシン　---　DNAジャイレース	","	アミカシン　---　リボソーム30Sサブユニット	","	ドキシサイクリン　---　リボソーム30Sサブユニット	","	メロペネム　---　ペニシリン結合蛋白	","	レボフロキサシン　---　シトクロムP450	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	68	,question:"	バイオアベイラビリティの高い抗真菌薬はどれか。2つ選べ。	",	level:	3	,choices:["	アムホテリシンB	","	カスポファンギン	","	フルコナゾール	","	ボリコナゾール	","	ミカファンギン	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	69	,question:"	急性糸球体腎炎について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	腰部叩打痛や細菌尿が見られる。	","	通常は一過性であり、予後良好である。	","	ペニシリン系薬による治療が必要である。	","	高齢者での主な発症契機は肺炎球菌性肺炎である。	","	A群溶連菌感染による場合にはASO・ASK抗体価が上昇する。	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	70	,question:"	結核に関する説明文として正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	高齢者のLTBIの発見動機としてコッホ現象が多い。	","	BCGはESAT-6とCFP-10を持つウシ型結核菌である。	","	コッホ現象が見られた場合には、結核感染を調べる検査を実施する。	","	IGRAの陽性コントロールとしてフィトヘマグルチニン（PHA）が用いられる。	","	コッホ現象とはツベルクリン反応を複数回実施することによって誘導される追加免疫効果のことである。	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	71	,question:"	真菌症について正しい説明はどれか。2つ選べ。	",	level:	4	,choices:["	肺結核後遺症は慢性肺アスペルギルス症の基礎疾患である。	","	夏型過敏性肺炎は播種性トリコスポロン症の危険因子である。	","	カンジダ血症の基礎疾患として後天性免疫不全症候群が最も多い。	","	侵襲性肺ムーコル症の診断には血清ガラクトマンナン抗原が有用である。	","	肺クリプトコックス症の診断には血清グルクロノキシロマンナン抗原が有用である。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	72	,question:"	真菌について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Cryptococcus neoformans</em>の莢膜の主成分はグルクロノキシロマンナンである。	","	<em>Aspergillus fumitatus</em>は消化管の常在真菌である。	","	<em>Candida tropicalis</em>は鵞口瘡の原因として最も多い。	","	肺結核後遺症は慢性肺アスペルギルス症の基礎疾患である。	","	<em>Rhizopus oryzae</em>は夏型過敏性肺炎の原因として最も多い。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	73	,question:"	ニューモシスチス肺炎の治療薬として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	アトバコン	","	ペンタミジン	","	ボリコナゾール	","	アムホテリシンB	","	スルファメトキサゾール/トリメトプリム	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	74	,question:"	抗真菌薬の説明として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	4	,choices:["	ミカファンギンはβ-D-グルカンの合成を阻害する。	","	フルコナゾールはカンジダ属に対しては静菌的に作用する。	","	5-FCは5-FUに変換されることで真菌の核酸合成を阻害する。	","	リポソーマルアムホテリシンは可溶性を改善したプロドラッグである。	","	ホスフルコナゾールはバイオアベイラビリティを改善したプロドラッグである。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	75	,question:"	バンコマイシンが<b><u>無効な</u></b>細菌はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Escherichia coli</em>	","	<em>Clostridioides difficile</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Staphylococcus epidermidis</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	76	,question:"	髄膜炎の鑑別において、ウイルス性よりも細菌性を強く疑う所見として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	項部硬直	","	体温 38度	","	髄液中の糖 8 mg/dL	","	jolt accentuation陽性	","	好中球優位の髄液中細胞数増加	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	77	,question:"	細菌性髄膜炎で低下する値はどれか。	",	level:	3	,choices:["	髄液ADA	","	髄液糖	","	髄液蛋白	","	髄液細胞数	","	髄液圧（初圧）	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	78	,question:"	性感染症の主要な病原体はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Plasmodium vivax</em>	","	<em>Neisseria meningitidis</em>	","	<em>Chlamydia trachomatis</em>	","	<em>Human papilloma virus</em>	","	<em>Cryptococcus neoformans</em>	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	79	,question:"	蚊によって媒介される感染症はどれか。2つ選べ。	",	level:	2	,choices:["	Rabies	","	Malaria	","	Smallpox	","	Chickenpox	","	West Nile fever	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	80	,question:"	TORCH症候群の病原体はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Cryptococcus gattii</em>	","	<em>Toxoplasma gondii</em>	","	<em>Treponema pallidum</em>	","	<em>Orientia tsutsugamuchi</em>	","	<em>Haemophilus parainfluenzae</em>	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	81	,question:"	<em>Streptococcus pneumoniae</em>について正しいのはどれか。2つ選べ。	",	level:	2	,choices:["	外膜を有する。	","	完全溶血性を示す。	","	普通寒天培地で良好に発育する。	","	健常児からもしばしば分離される。	","	5%の二酸化炭素によって発育が促進される。	"],	correct:[				"d",	"e",	],explanation:"	<br><span class='kakomon'>感統</span>2024本試験-<strong>問題1</strong>	",	selectionCount:	2	},		
{id:	82	,question:"	糞便の塗抹染色を行って感染性下痢症の原因菌の診断が可能な菌はどれか。	",	level:	2	,choices:["	<em>Shigella sonnei</em>	","	<em>Anisakis simplex</em>	","	<em>Salmonella</em> Typhi	","	<em>Camplylobacter jejuni/coli</em>	","	enterohaemorrhagic <em>Escherichia coli</em>	"],	correct:[				"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	83	,question:"	喀痰検査に関する説明として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	2	,choices:["	Geckler分類では、G5が最も診断価値が⾼い。	","	Miller-Jones分類は、喀痰の⾁眼的分類である。	","	Miller-Jones分類で、M1が最も診断価値が⾼い。	","	顕微鏡で貪⾷像が⾒られた場合には、コンタミネーションが疑われる。	","	Geckler分類のG5は、顕微鏡下で扁平上⽪が少なく好中球が多いのが特徴である。	"],	correct:[			"c",	"d",		],explanation:"	<br><span class='kakomon'>感統</span>2024本試験-<strong>問題2</strong>	",	selectionCount:	2	},		
{id:	84	,question:"	人工培地での培養が可能な細菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Pneumocystis jirovecii</em>	","	<em>Orientia tsutsugamushi</em>	","	<em>Chlamydia trachomatis</em>	","	<em>Legionella pneumophila</em>	","	<em>Mycobacterium tuberculosis</em>	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	85	,question:"	アルコールが<b><u>無効な</u></b>病原体はどれか。	",	level:	2	,choices:["	<em>Candida albicans</em>	","	<em>Clostridioides difficile</em>	","	<em>Pseudomonas aeriginosa</em>	","	enterohemorrhagic <em>Escherichi coli</em>	","	methicillin-resistant <em>Staphylococcus aureus</em>	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	86	,question:"	結核および結核菌について正しいものはどれか。2つ選べ。	",	level:	4	,choices:["	芽胞形成菌である。	","	倍加時間は2〜5時間である。	","	感染症法では2類感染症に定められている。	","	第2種病原体であり、取り扱いには⼤⾂の許可が必要である。	","	検査室内での感染を防ぐため、取り扱い時にはN95マスクを着⽤する。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	87	,question:"	血液培養から分離された場合、汚染菌の可能性が高い菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Escherichia coli</em>	","	<em>Bacillus subtilis</em>	","	<em>Cutibacterium acnes</em>	","	<em>Staphylococcus aureus</em>	","	<em>Pseudomonas aeruginosa</em>	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	88	,question:"	インターフェロンγ遊離検査（IGRA）の基準値を設定するために使用される陰性および陽性コントロールはどれか。2つ選べ。	",	level:	3	,choices:["	無刺激	","	CFP-10	","	ESAT-6	","	インターフェロンγ	","	マイトジェン（PHA）	"],	correct:[	"a",				"e",	],explanation:"	無刺激は陰性コントロール、マイトジェンは陽性コントロール。CFP-10とESAT-6は結核特異的抗原である。インターフェロンγは測定する物質であり、抗原としては含まれない。	",	selectionCount:	2	},		
{id:	89	,question:"	ツベルクリン反応に用いられる抗原はどれか。	",	level:	4	,choices:["	Galactomannan (GM)	","	Glucuronoxylomannan (GXM)	","	Rapid plasma reagin (RPR)	","	Phytohemagglutinin (PHA)	","	Purified protein derivative (PPD)	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	90	,question:"	<em>Streptococcus pyogenes</em>について正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	β溶血性を示す。	","	コロナ禍で大流行が報告された。	","	ペニシリン系薬に自然耐性を示す。	","	Lancefield分類のA群に分類される。	","	<em>emm1</em>はマクロライド耐性遺伝子である。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	91	,question:"	アルコールが効きにくい病原体はどれか。2つ選べ。	",	level:	2	,choices:["	ノロウイルス	","	インフルエンザウイルス	","	カルバペネム耐性大腸菌	","	メチシリン耐性黄色ブドウ球菌	","	ディフィシル菌	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	92	,question:"	潜伏期間が最も長い感染症はどれか。	",	level:	2	,choices:["	カンピロバクター腸炎	","	コレラ	","	結核	","	細菌性赤痢	","	腸管出血性大腸菌感染症	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	93	,question:"	空気感染する病原体はどれか。2つ選べ。	",	level:	2	,choices:["	結核菌	","	緑膿菌	","	麻疹ウイルス	","	SARSコロナウイルス	","	インフルエンザウイルス	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	94	,question:"	標準予防策〈standard precautions〉について正しいのはどれか。	",	level:	2	,choices:["	患者を隔離する。	","	医療者の手指衛生を徹底する。	","	感染症と診断してから開始する。	","	感染症の治療が済んだら終了する。	","	特定の感染症への対策として実施する。	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	95	,question:"	最も感染力（基本再生産数）の高い感染症はどれか。	",	level:	2	,choices:["	結核	","	麻疹	","	SARS	","	COVID-19	","	インフルエンザ	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	96	,question:"	エンベロープを持たないウイルスはどれか。2つ選べ。	",	level:	2	,choices:["	ノロウイルス	","	風疹ウイルス	","	麻疹ウイルス	","	A型肝炎ウイルス	","	B型肝炎ウイルス	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	97	,question:"	感染症と原因病原体の組合せとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	野兎病　---　<em>Brucella melitensis</em>	","	百日咳　---　<em>Bordetella pertussis</em>	","	猫ひっかき病　---　<em>Bartonella henselae</em>	","	特発性器質化肺炎　---　<em>Haemophilus influenzae</em>	","	人工呼吸器関連肺炎　---　<em>Streptococcus pneumoniae</em>	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	98	,question:"	偏性細胞内増殖菌はどれか。	",	level:	1	,choices:["	<em>Bordetella pertussis</em>	","	<em>Chlamydia trachomatis</em>	","	<em>Haemophilus influenzae</em>	","	<em>Mycoplasma pneumoniae</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	99	,question:"	培地と病原体の組み合わせのうち正しいのはどれか。 2つ選べ。	",	level:	4	,choices:["	小川培地　---　<em>Mycobacterium tuberculosis</em>	","	血液寒天培地　---　<em>Haemophilus influenzae</em>	","	Skirrow培地　---　<em>Pseudomonas aeruginosa</em>	","	BCYE-α培地　---　<em>Candida albicans</em>	","	PPLO培地　---　<em>Mycoplasma pneumoniae</em>	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	100	,question:"	インフルエンザ菌による感染症として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	2	,choices:["	急性胆嚢炎	","	急性中耳炎	","	急性副鼻腔炎	","	急性膀胱炎	","	細菌性髄膜炎	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	101	,question:"	80歳、男性。誤嚥性肺炎の治療のためアンピシリン／スルバクタムの投与を開始したところ、8日目から下腹部痛と下痢症状を訴え、9日目には１日８回の水様性下痢が認められた。このときのBristol Stool Scaleは何点か。	",	level:	2	,choices:["	1点	","	2点	","	4点	","	5点	","	7点	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	102	,question:"	80歳、男性。誤嚥性肺炎の治療のためアンピシリン／スルバクタムの投与を開始したところ、8日目から下腹部痛と下痢症状を訴え、9日目には１日８回の水様性下痢が認められた。本症の診断に有用な検査はどれか。2つ選べ。	",	level:	3	,choices:["	便のグラム染色	","	便中のGDHの測定	","	血中のバイナリトキシンの測定	","	便中のトキシンA・トキシンBの測定	","	血中のトキシンA・トキシンBの測定	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	103	,question:"	80歳、男性。誤嚥性肺炎の治療のためアンピシリン／スルバクタムの投与を開始したところ、8日目から下腹部痛と下痢症状を訴え、9日目には１日８回の水様性下痢が認められた。本症に対する感染予防策として正しいのはどれか。	",	level:	2	,choices:["	標準予防策を解除する。	","	標準予防策のみを行う。	","	飛沫予防策を行う。	","	空気予防策を行う。	","	接触予防策を行う。	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	104	,question:"	80歳、男性。誤嚥性肺炎の治療のためアンピシリン／スルバクタムの投与を開始したところ、8日目から下腹部痛と下痢症状を訴え、9日目には１日８回の水様性下痢が認められた。本症に対する治療薬として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	クリンダマイシン	","	バンコマイシン	","	フィダキソマイシン	","	メトロニダゾール	","	メロペネム	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	105	,question:"	セファロスポリン系薬が<b><u>無効な</u></b>細菌はどれか。2つ選べ。	",	level:	4	,choices:["	<em>Acinetobacter baumannii</em>	","	<em>Enterococcus faecium</em>	","	<em>Escherichia coli</em>	","	<em>Listeria monocytogenes</em>	","	<em>Pseudomonas aeruginosa</em>	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	106	,question:"	β-ラクタマーゼ阻害薬はどれか。2つ選べ。	",	level:	3	,choices:["	クラブラン酸	","	シラスタチン	","	タゾバクタム	","	ピボキシル	","	ベタミプロン	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	107	,question:"	抗微生物薬と副作用の組み合わせとして適切なのはどれか。2つ選べ。	",	level:	3	,choices:["	アンピシリン　－　悪性症候群（Syndrome malin）	","	イソニアジド　－　乳酸アシドーシス	","	オセルタミビル　－　gray baby症候群	","	ピラジナマイド　－　高尿酸血症	","	ミノサイクリン　－　歯牙着色	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	108	,question:"	メチシリン感受性黄色ブドウ球菌による蜂窩織炎の第一選択薬はどれか。	",	level:	3	,choices:["	セファゾリン	","	バンコマイシン	","	アジスロマイシン	","	クリンダマイシン	","	テトラサイクリン	"],	correct:[	"a",					],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	109	,question:"	Ambler分類class Aのβ-ラクタマーゼはどれか。2つ選べ。	",	level:	5	,choices:["	CTX-M-9	","	IMP-6	","	KPC1	","	Mcr1	","	NDM1	"],	correct:[	"a",		"c",			],explanation:"	👉 <a href='http://filgap.kenkyuukai.jp/special/?id=42864#ambler' target='_blank'>Ambler分類</a>	",	selectionCount:	2	},		
{id:	110	,question:"	多剤耐性緑膿菌の基準となる抗菌薬はどれか。全て選べ。	",	level:	3	,choices:["	アミカシン	","	イミペネム	","	クラリスロマイシン	","	シプロフロキサシン	","	セフタジジム	"],	correct:[	"a",	"b",		"d",		],explanation:"	👉 <a href='http://filgap.kenkyuukai.jp/special/?id=41990#mdrp' target='_blank'>MDRP</a>	",	selectionCount:	"all"	},		
{id:	111	,question:"	基質特異性拡張型β-ラクタマーゼについて正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	CTX-M型が主流である。	","	染色体性で伝達性がない。	","	Ambler分類のClass Aに属する。	","	カルバペネム系薬まで分解できる。	","	主に<em>Enterococcus</em>属の細菌が保有する。	"],	correct:[	"a",		"c",			],explanation:"	ESBLは近年増加している耐性因子であり、主な産生菌は腸内細菌科細菌、特に、大腸菌と肺炎桿菌である。Ambler分類ではクラスAに分類される。CTX－M型が主流であり、大腸菌では特定のST型（ST131）との関連が知られている。プラスミド性であり伝達性があることも問題である。セファロスポリン系薬は分解するが、セファマイシン系薬やカルバペネム系薬は分解しない。<br>👉 <a href='http://filgap.kenkyuukai.jp/special/?id=42864#esbl' target='_blank'>ESBL</a>	",	selectionCount:	2	},		
{id:	112	,question:"	バンコマイシン耐性腸球菌（VRE）について正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	VanA型はバンコマイシンにのみ耐性化する。	","	VanB型はテイコプラニンにのみ耐性化する。	","	VanA型の多くはプラスミド性であり、伝達性がある。	","	便や尿から分離された場合、7日以内に最寄りの保健所に届け出る必要がある。	","	<em>Enterococcus faecium</em>の方が、<em>Enterococcus faecalis</em>よりもVREとして分離されやすい。	"],	correct:[			"c",		"e",	],explanation:"	感染症法上の届出の基準は感染症であるため、定着のみでは届け出の対象とならない。しかしながら、VREが検出された場合には、接触予防策などの拡散防止の必要性の有無を考慮する必要がある。また、抗菌薬の適正使用に関しても注意が必要である。VanAもVanBも誘導型であるが、VanAはバンコマイシンとテイコプラニンの両方で誘導される一方、VanBはバンコマイシンでのみ誘導される。また、VanAはプラスミド性、VanBは染色体性である。VREとして分離されるのは、<em>Enterococcus faecium</em>が多い。	",	selectionCount:	2	},		
{id:	113	,question:"	AMR対策アクションプラン（2023-2027）で示されている2027年までの数値目標に関する説明として正しいのはどれか。	",	level:	5	,choices:["	ヒトに関して、肺炎球菌のマクロライド耐性率を10%以下にすることが示されている。	","	ヒトに関して、黄色ブドウ球菌のメチシリン耐性率を20%以下にすることが示されている。	","	大腸菌のテトラサイクリン耐性率は、ヒトと動物の両方に関する数値目標が示されている。	","	ヒトに関して、注射用ペニシリン系薬の人口千人当たりの一日使用量を2020年比で20%増にすることが示されている。	","	ヒトに関して、経口第一世代セファロスポリン系薬の人口千人当たりの一日使用量を2020年比で40%減にすることが示されている。	"],	correct:[		"b",			"e",	],explanation:"	ヒトに関する数値目標は、バンコマイシン耐性腸球菌感染症、黄色ブドウ球菌のメチシリン耐性率、大腸菌のフルオロキノロン耐性率、緑膿菌のカルバペネム耐性率、大腸菌・肺炎桿菌のカルバペネム耐性率、人口千人当たりの一日抗菌薬使用量、経口第三世代セファロスポリン系薬・経口フルオロキノロン系薬・経口マクロライド系薬・カルバペネム系の静注抗菌薬の人口千人当たりの一日使用量の数値目標が示されている。	",	selectionCount:	2	},		
{id:	114	,question:"	尿路感染症の主な原因菌はどれか。	",	level:	3	,choices:["	<em>Escherichia coli</em>	","	<em>Bacteroides fragilis</em>	","	<em>Staphylococcus aureus</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Streptococcus agalactiae</em>	"],	correct:[	"a",					],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	115	,question:"	2セット採取した血液培養のうち、好気ボトルのみグラム陰性桿菌が検出された場合に、最も考えられる原因菌はどれか。2つ選べ。	",	level:	4	,choices:["	<em>Escherichia coli</em>	","	<em>Staphylococcus aureus</em>	","	<em>Haemophilus influenzae</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Acinetobacter baumannii</em>	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	116	,question:"	蛋白合成を阻害する抗菌薬はどれか。2つ選べ。	",	level:	2	,choices:["	アモキシシリン	","	クラリスロマイシン	","	シプロフロキサシン	","	ミノサイクリン	","	リファンピシン	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	117	,question:"	真菌症と検査の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	カンジダ症　－　β-Dグルカン	","	肺クリプトコックス症　－　血清グルクロノキシロマンナン抗原	","	侵襲性肺アスペルギルス症　－　血清アスペルギルス抗体	","	播種性トリコスポロン症　－　血清ガラクトマンナン抗原	","	ニューモシスチス肺炎　－　インターフェロンγ遊離検査	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	118	,question:"	抗菌薬と投与回数の組み合わせとして正しいのはどれか。2 つ選べ。	",	level:	4	,choices:["	セフトリアキソン --- 1 日1 回	","	レボフロキサシン --- 1 日1 回	","	メロペネム --- 1 日1 回	","	アルベカシン --- 1 日4 回	","	セファゾリン --- 1 日1 回	"],	correct:[	"a",	"b",				],explanation:"	β-ラクタム系薬は時間依存性であり、基本的には1日3～4回程度に分割して投与する抗菌薬が多い。ただし、セフトリアキソンは半減期が長いため1日1（～2）回での投与が可能である。一方、フルオロキノロンは濃度依存性であり、1日1回の投与が原則である。	",	selectionCount:	2	},		
{id:	119	,question:"	静菌的な作用を示す抗菌薬はどれか。2 つ選べ。	",	level:	3	,choices:["	クラリスロマイシン	","	バンコマイシン	","	メロペネム	","	リネゾリド	","	レボフロキサシン	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	120	,question:"	血液培養の採取について正しいのはどれか。2 つ選べ。	",	level:	3	,choices:["	好気ボトルよりも嫌気ボトルに先に入れる。	","	好気用と嫌気用はそれぞれ別の部位から採血する。	","	血液培養のボトルのゴム栓部分はアルコールで消毒する。	","	採血部位はアルコールで消毒してはならない。	","	黄色ブドウ球菌が培養されたら汚染菌と判断する。	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	121	,question:"	B細胞を標的とする生物学的製剤はどれか。	",	level:	4	,choices:["	ゲフィチニブ	","	フィルグラスチム	","	ベズロトクスマブ	","	リツキシマブ	","	レカネマブ	"],	correct:[				"d",		],explanation:"	リツキシマブはCD20陽性のB細胞を標的とするモノクローナル抗体である。	",	selectionCount:	1	},		
{id:	122	,question:"	病原体に関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	<em>Streptococcus pneumoniae</em>はβ溶血性を示す。	","	<em>Enterococcus faecium</em>は腸内細菌科細菌である。	","	<em>Legionella pneumophila</em>は鳥類に寄生している。	","	<em>Haemophilus influenzae</em>は発育にX因子とV因子を必要とする。	","	<em>Helicobacter pylori</em>は尿素を加水分解してアンモニアと二酸化炭素を発生する。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	123	,question:"	疾患と病原体の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	Creutzfeldt-Jakob disease　---　JC virus	","	epidemic typhus　---　<em>Salmonella</em> Typhi	","	gas gangrene　---　<em>Clostridium perfringens</em>	","	amoebic dysentery　---　<em>Acanthamoeba castellanii</em>	","	Lemierre syndrome　---　<em>Fusobacterium necrophorum</em>	"],	correct:[						],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	124	,question:"	検査とその原理の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	LAMP　---　核酸増幅	","	TPHA　　---　赤血球凝集	","	RT-QUIC　---　RNAの増幅	","	ELISA　---　放射性同位元素を用いたIgEの検出	","	IGRA　---　血清によるマクロファージの分化誘導	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	125	,question:"	疾患に関する説明として正しいのはどれか。	",	level:	3	,choices:["	腸チフスでは比較的徐脈が見られる。	","	マイコプラズマ肺炎では高IgEが見られる。	","	マイコプラズマ肺炎では尿のPCRが診断に有用である。	","	三日熱マラリアは約48時間おきに発熱が繰り返される。	","	梅毒の発病予防として暴露後のペニシリン内服が推奨される。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	126	,question:"	腎機能の指標となる検査値はどれか。2つ選べ。	",	level:	2	,choices:["	尿酸	","	LDH	","	eGFR	","	HbA1c	","	クレアチニン	"],	correct:[			"c",		"e",	],explanation:"	<br><span class='kakomon'>感統</span>2024本試験-<strong>問題39</strong>	",	selectionCount:	2	},		
{id:	127	,question:"	肝障害の指標となる検査値はどれか。2つ選べ。。	",	level:	2	,choices:["	尿酸	","	HbA1c	","	クレアチニン	","	ALT（GPT）	","	AST（GOT）	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	128	,question:"	糖尿病コントロールの指標となる検査値はどれか。2つ選べ。	",	level:	2	,choices:["	LDH	","	HbA1c	","	クレアチニン	","	ALT（GPT）	","	血糖値（食後2時間）	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	129	,question:"	樹状細胞について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	粘膜には樹状細胞がない。	","	樹状細胞はT細胞から抗原提示を受ける。	","	樹状細胞は皮内よりも筋肉内に多く存在する。	","	樹状細胞は皮下組織よりも皮内に多く存在する。	","	樹状細胞は皮下組織よりも筋肉内に多く存在する。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	130	,question:"	主要組織適合性複合体（MHC）について正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	class I分子はCD2と共発現する。	","	class I分子は全ての有核細胞が持つ。	","	ヒトではヒト白血球抗原（HLA）に相当する。	","	class II分子は主に内在性抗原を提示する。	","	class I分子はclass IIよりも大きなペプチド断片を提示する。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	131	,question:"	サイトカインについて正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	IL-8はケモカインである。	","	EGFはがん抑制因子である。	","	TNF-αは好中球遊走因子である。	","	IL-10は抗炎症性サイトカインである。	","	G-CSFはマクロファージ増殖因子である。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	132	,question:"	後天性免疫不全症候群（AIDS）におけるニューモシスチス肺炎（PCP）について正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	胸部CTでは異常を認めない。	","	血清β-Dグルカンが高値である。	","	ステロイド治療中のPCPに比べて菌量が多い。	","	ステロイド治療中のPCPに比べて肺の損傷が強い。	","	AIDSの治療を優先し、CD4陽性細胞数が200/μL以上になってからPCPの治療を開始する。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	133	,question:"	<em>Pneumocystis jirovecii</em>について正しい説明はどれか。2つ選べ。	",	level:	4	,choices:["	細胞壁を有する。	","	真核生物である。	","	元々イヌから分離された。	","	種名は日本人の名前に由来する。	","	培養にはサブロー培地を用いる。	"],	correct:[	"a",	"b",				],explanation:"	<br><span class='kakomon'>感統</span>2024本試験-<strong>問題40</strong>	",	selectionCount:	2	},		
{id:	134	,question:"	ニューモシスチス肺炎を起こしやすい状態はどれか。2つ選べ。	",	level:	3	,choices:["	HbA1cが6.5%である。	","	CD4陽性細胞が20/μLである。	","	eGFRが85.5mL/min/1.732である。	","	プレドニゾロン5mg/日を2週間内服中である。	","	インフリキシマブ（抗TNFα抗体）による治療中である。	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	135	,question:"	<em>Pneumocystis jirovecii</em>について正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	担子菌門に属する。	","	染色体は4本である。	","	ゲノムサイズは約1Mbpである。	","	ギムザ染色では嚢子よりも栄養体がよく染まる。	","	グロコット染色では栄養体よりも嚢子がよく染まる。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	136	,question:"	後天性免疫不全症候群（AIDS）におけるニューモシスチス肺炎（PCP）について正しい説明はどれか。2つ選べ。	",	level:	5	,choices:["	低酸素を認めない。	","	KL-6が高値となる。	","	第一選択薬はST合剤である。	","	ステロイド治療中のPCPに比べて予後が悪い。	","	ステロイドを併用している場合にはステロイドを中止する。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	137	,question:"	結核の感染診断に用いる検査法はどれか。2つ選べ。	",	level:	3	,choices:["	LAMP法	","	薬剤リンパ球刺激試験（DLST）	","	ツベルクリン皮内反応（ツ反）	","	インターフェロンγ遊離試験（IGRA）	","	DNA-DNAハイブリダイゼーション（DDH）	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	138	,question:"	インターフェロンγ遊離試験（IGRA）について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	採血前に皮下に抗原を接種する。	","	陰性であれば潜在性結核感染症と診断する。	","	陽性であれば結核に対する免疫があり、再感染しないことを意味する。	","	T-SPOT.TBは、結核菌特異的抗原に反応するT細胞からのインターフェロンγ産生細胞の数を測定する検査である。	","	QuantiFERON-TB Gold（QFT）は結核菌特異的抗原に対するT細胞からのインターフェロンγの産生量を測定する検査である。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	139	,question:"	インターフェロンγ遊離試験（IGRA）について<b><u>誤っている</u></b>はどれか。2つ選べ。	",	level:	3	,choices:["	採血管にIL-8を加えておく。	","	陰性であればBCG接種が必要である。	","	陽性コントロールが低値の場合、判定保留となる。	","	陽性コントロールにフィトヘマグルチニン（PHA）などのマイトジェンを用いる。	","	結核菌特異的抗原に反応してインターフェロンγを産生するT細胞の活性を評価する。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	140	,question:"	免疫クロマト法について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	標識抗体を用いる。	","	PCRよりも感度が高い。	","	IGRAの原理を用いている。	","	測定時間は約2時間である。	","	インフルエンザの診断に利用されている。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	141	,question:"	潜在性結核感染症（LTBI）について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	診断にはPCRが最も有用である。	","	結核菌が体内で活発に増殖している。	","	2類感染症として保健所に届け出る必要がある。	","	無治療では2か月以内に80%が活動性結核に進展する。	","	イソニアジドとリファンピシンの2剤で3～4か月治療を行う。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	142	,question:"	インターフェロンγ遊離試験（IGRA）とツベルクリン皮内反応（ツ反）の違いについて正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	ツ反は48時間後に判定を行う。	","	ツ反は採血を行う必要がある。	","	IGRAはBCG接種の影響を受けない。	","	SLEではツ反が陽性になりやすい。	","	妊婦ではIGRAが陽性になりやすい。	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	143	,question:"	梅毒血清反応（STS）において生物学的偽陽性を認めやすいのはどれか。2つ選べ。	",	level:	3	,choices:["	妊娠	","	B型肝炎	","	C型肝炎	","	慢性関節リウマチ	","	全身性ループスエリテマトーデス（SLE）	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	144	,question:"	梅毒の治療ついて正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	病期によって治療期間が異なる。	","	ペニシリン系薬が第一選択である。	","	STSが陰性化するまで治療を継続する。	","	TPHAが陰性化するまで治療を継続する。	","	治療開始後、悪寒戦慄を認めたら治療を中止する。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	145	,question:"	成人の標準的な上腕部の筋肉注射について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	皮膚を伸展して穿刺する。	","	皮膚に対して垂直に穿刺する。	","	注射針の長さは12mm程度が適している。	","	三角筋と上腕三頭筋の境界に接種する。	","	三角筋部への接種で上方にずれた場合には橈骨神経損傷が起こりやすい。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	146	,question:"	薬力学（PD）のパラメーターはどれか。	",	level:	3	,choices:["	血中半減期	","	C反応性ペプチド（CRP）	","	最小発育阻止濃度（MIC）	","	推定糸球体ろ過量（eGFR）	","	血中濃度曲線下面積（AUC）	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	147	,question:"	疾患と病原体の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	Kuru　---　Epstein-Barr virus	","	amoebic keratitis　---　 <em>Amoebobacter roseus</em>	","	typhoid fever (enteric fever)　---　<em>Salmonella</em> Typhi	","	pseudomembranous colitis　---　<em>Clostridioides difficile</em>	","	Waterhouse-Friderichsen syndrome　---　<em>Chlamydia trachomatis</em>	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	148	,question:"	感染症に関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	梅毒の診断にはインターフェロンγ遊離検査が有用である。	","	クリプトコッカス症の診断には便中抗原検査が有用である。	","	狂犬病は発症後に免疫グロブリン投与を行うことで救命可能である。	","	クロイツフェルト・ヤコブ病では脳波で周期性同期放電が見られる。	","	アスペルギルス症の診断にはガラクトマンナン抗原検査が有用である。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	149	,question:"	腸内細菌科細菌に共通する特徴はどれか。2つ選べ。	",	level:	3	,choices:["	芽胞を形成する。	","	鞭毛を持たない。	","	通性嫌気性菌である。	","	ブドウ糖を分解し酸を産生する。	","	セファマイシン系薬に自然耐性を示す。	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	150	,question:"	リツキシマブによる治療を開始する前に実施すべき検査はどれか。2つ選べ。	",	level:	3	,choices:["	HBs抗原	","	HBc抗体	","	血液培養検査	","	肺炎球菌尿中抗原検査	","	インフルエンザ抗原検査	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	151	,question:"	鼻中隔前下部にある鼻出血の好発部位はどれか。	",	level:	3	,choices:["	Roth spots	","	McBurney's point	","	Auerbach's plexus	","	Kiesselbach's area	","	Hesselbach's triangle	"],	correct:[				"d",		],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	152	,question:"	疾患と特徴的な症状・所見の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	急性糸球体腎炎　---　血尿	","	リウマチ熱　---　比較的徐脈	","	ジカウイルス感染症　---　皮疹	","	ロア糸状虫症　---　遊走性紅斑	","	急性膀胱炎　---　肋骨脊柱角叩打痛	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	153	,question:"	免疫グロブリンに関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	IgEはFc領域を欠く。	","	主に肝臓で合成される。	","	IgAは胎盤移行性がある。	","	血液中ではIgGが最も多い。	","	IgMは血液中で5量体を形成している。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	154	,question:"	核酸について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	グアニンはプリン塩基である。	","	真核生物のDNAは核内にのみ限局している。	","	ヌクレオシドは塩基とリン酸で構成される。	","	アデニンはシトシンと2つの水素結合で対になっている。	","	RNAの塩基としてチミンの代わりにウラシルが用いられている。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	155	,question:"	ヒト免疫不全ウイルス（HIV）感染症の予防・治療について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	HIVの暴露後予防内服は一生継続する必要がある。	","	AIDS発症後の抗レトロウイルス療法は3剤以上を併用する。	","	HIVの暴露後予防内服は核酸系逆転写酵素阻害薬単剤で行う。	","	HIV感染症の治療はCD4陽性細胞が400/μL以上になれば中止できる。	","	HIVの治療によって検出限界未満に維持できれば、性行為による感染は起こらない。	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	156	,question:"	damage associated molecular patterns (DAMPs)はどれか。	",	level:	3	,choices:["	dectin-1	","	β-D-glucan	","	lipopolysaccharide	","	toll-like receptor 4	","	high mobility group box-1	"],	correct:[					"e",	],explanation:"	<br><span class='kakomon'>感統</span>2024本試験-<strong>問題60</strong>	",	selectionCount:	1	},		
{id:	157	,question:"	筋肉接種しなければならないワクチンはどれか。2つ選べ。	",	level:	3	,choices:["	MRワクチン	","	HPVワクチン	","	水痘ワクチン	","	結合型肺炎球菌ワクチン（PCV15）	","	新型コロナワクチン（mRNAワクチン）	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	158	,question:"	ピロリ菌が原因となる疾患はどれか。2つ選べ。	",	level:	3	,choices:["	硬性下疳	","	軟性下疳	","	骨髄繊維症	","	悪性リンパ腫	","	免疫性血小板減少症	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	159	,question:"	内視鏡を⽤いずに⾏うピロリ菌感染症の診断法はどれか。2つ選べ。	",	level:	3	,choices:["	培養法	","	組織鏡検法	","	便中抗原検査	","	尿素呼気テスト	","	迅速ウレアーゼ試験	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	160	,question:"	 ピロリ菌感染症の⼀次除菌に⽤いる薬剤はどれか。2つ選べ。	",	level:	3	,choices:["	クラリスロマイシン	","	ピペラシリン	","	シメチジン	","	ランソプラゾール	","	バンコマイシン	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	161	,question:"	偏性嫌気性菌はどれか。	",	level:	3	,choices:["	<em>Clostridioides difficile</em>	","	<em>Legionella pneumophila</em>	","	<em>Mycoplasma pneumoniae</em>	","	<em>Fusobacterium necrophorum</em>	","	<em>Mycobacterium intracellulare</em>	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	162	,question:"	口腔カンジダ症の基礎疾患または危険因子として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	BCG接種歴	","	ステロイドの内服	","	後天性免疫不全症候群	","	フルコナゾールの内服	","	CD4陽性細胞が400/μL以上	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	163	,question:"	播種性カンジダ症の基礎疾患または危険因子として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	BCG接種歴	","	ミカファンギンの投与	","	アムホテリシンBの投与	","	好中球数が500/μL未満	","	中心静脈カテーテルの留置	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	164	,question:"	Fitz-Hugh-Curtis症候群の原因菌として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	<em>Moraxella catarrhalis</em>	","	<em>Mycobacterium leprae</em>	","	<em>Neisseria gonorrhoeae</em>	","	<em>Chlamydia trachomatis</em>	","	<em>Mycoplasma pneumoniae</em>	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	165	,question:"	Waterhouse-Friderichsen症候群の原因菌として正しいのはどれか。	",	level:	3	,choices:["	<em>Chlamydia psittaci</em>	","	<em>Neisseria meningitis</em>	","	<em>Moraxella catarrhalis</em>	","	<em>Legionella pneumophila</em>	","	<em>Mycobacterium tuberculosis</em>	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	166	,question:"	溶血性尿毒症症候群の病態として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	血小板数が低下する。	","	ヘモグロビン値が低下する。	","	ALT（GPT）が低下する。	","	高ナトリウム血症になりやすい。	","	血清クレアチニン値が低下する。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	167	,question:"	ヒト型結核菌のRD1領域に含まれる遺伝子がコードする蛋白はどれか。2つ選べ。	",	level:	3	,choices:["	 KatG	","	 MCR1	","	 QRDR	","	 CFP-10	","	 ESAT-6	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	168	,question:"	脳神経の番号と脳神経の名称の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	II　---　視神経	","	V　---　三叉神経	","	VI　---　顔面神経	","	VII　---　動眼神経	","	VIII　---　迷走神経	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	169	,question:"	トリアゾール系抗真菌薬はどれか。2つ選べ。	",	level:	3	,choices:["	Omeprazole	","	Fluconazole	","	Voriconazole	","	Lansoprazole	","	Metronidazole	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	170	,question:"	 核酸増幅検査はどれか。2つ選べ。	",	level:	3	,choices:["	Western blotting	","	Radioallergosorbent test	","	Polymerase chain reaction	","	Enzyme-linked immuno sorbent assay	","	Loop-mediated isothermal amplification	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	171	,question:"	滅菌・消毒について正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	手指消毒には30%のエタノールが適している。	","	オートクレーブは芽胞を滅菌することができる。	","	100％のエタノールで芽胞を滅菌することができる。	","	プリオンは100℃の煮沸により不活化することができる。	","	オートクレーブは、2気圧、121℃の高圧蒸気を用いる方法である。	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	172	,question:"	28歳の女性。外陰潰瘍を主訴に来院した。10日前に潰瘍に気付いたが痛みがないので様子をみていた。身長164cm、体重58kg。体温36.5℃。脈拍72/分、整。血圧124/76mmHg。呼吸数20/分。左小陰唇外側に径10mmの硬結を認め、中心に潰瘍を認める。自発痛と圧痛はない。両側鼠径部のリンパ節に径1cmの腫大を触知するが痛みはない。可能性が高いのはどれか。（第115回医師国家試験D59より一部改変）	",	level:	3	,choices:["	梅毒	","	淋菌感染症	","	性器ヘルペス	","	クラミジア感染症	","	尖圭コンジローマ	"],	correct:[	"a",					],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	173	,question:"	感染症と診断に有用な染色法の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	結核　---　Papanicolaou染色	","	マラリア　---　 May-Giemsa染色	","	伝染性単核球症　---　 Grocott染色	","	レジオネラ肺炎　---　Gimenez染色	","	マイコプラズマ肺炎　---　Ziehl-Neelsen染色	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	174	,question:"	主としてマダニが媒介する疾患はどれか。2つ選べ。（第106回医師国家試験G16より一部改変）	",	level:	3	,choices:["	重症熱性血小板減少症候群	","	マラリア	","	ライム病	","	リーシュマニア感染症	","	ペスト	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	175	,question:"	Which of the following pathogens of pneumonia is the urinary antigen test available for in diagnosis? Choose two.	",	level:	2	,choices:["	<em>Chlamydia psittaci</em>	","	<em>Mycobacterium avium</em>	","	<em>Legionella pneumophila</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	176	,question:"	Which of the following pathogens are obligate intracellular pathogens? Choose two.	",	level:	2	,choices:["	<em>Acinetobacter baumannii</em>	","	<em>Chlamydia trachomatis</em>	","	<em>Haemophilus influenzae</em>	","	<em>Mycoplasma pneumoniae</em>	","	<em>Orientia tsutsugamushi</em>	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	177	,question:"	病原体に関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	<em>Streptococcus pneumoniae</em>はβ溶血性を示す。	","	<em>Enterococcus faecium</em>は腸内細菌科細菌である。	","	<em>Pseudomonas aeruginosa</em>はブドウ糖を発酵し酪酸を産生する。	","	<em>Haemophilus influenzae</em>は発育にX因子とV因子を必要とする。	","	<em>Helicobacter pylori</em>は尿素を加水分解してアンモニアと二酸化炭素を発生する。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	178	,question:"	抗酸菌染色に用いる染色液はどれか。2つ選べ。	",	level:	3	,choices:["	クリスタルバイオレット	","	サフラニン	","	石炭酸フクシン	","	メチレンブルー	","	ヘマトキシリン	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	179	,question:"	結核ワクチンおよび診断について、正しいものを2つ選べ。	",	level:	3	,choices:["	BCGは結核菌群が持つRD1領域を欠く。	","	IGRA検査で陽性化するのは結核菌群のみである。	","	ツベルクリン反応の陽性化はBCG接種の影響を受けない。	","	乳児のBCG接種でコッホ現象が見られた場合は結核感染を疑う。	","	IGRAは結核菌特異抗原に対する液性免疫を指標とする診断法である。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	180	,question:"	非結核性抗酸菌はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Mycobacterium bovis</em>	","	<em>Mycobacterium leprae</em>	","	<em>Mycobacterium kansasii</em>	","	<em>Mycobacterium tuberculosis</em>	","	<em>Mycobacterium intracellulare</em>	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	181	,question:"	食中毒原因菌のうち、3類感染症の原因菌として誤っているものを2つ選べ。	",	level:	3	,choices:["	<em>Vibrio cholerae</em>	","	<em>Shigella sonnei</em>	","	<em>Yersinia enterocolitica</em>	","	<em>Salmonella</em> Typhimurium	","	Enterohemorrhagic <em>Escherichia coli</em>	"],	correct:[			"c",		"d",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	182	,question:"	食中毒原因菌とその症状の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	<em>Shigella sonnei</em> ----- しぶり腹	","	<em>Vibrio cholerae</em> ----- 偽虫垂炎症候群	","	<em>Bacillus cereus</em> ----- 嘔吐	","	<em>Yersinia enterocolitica</em> ----- 目の充血、いちご舌、手足の紅斑	","	<em>Salmonella</em> Typhimurium ----- バラ疹、稽留熱	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	183	,question:"	ボツリヌス感染症に関する説明として誤っているのはどれか。2つ選べ。	",	level:	3	,choices:["	DPTワクチンによる予防が可能である。	","	乳児に蜂蜜を与える場合は100˚Cで5分以上加熱したものを与える。	","	真空パック等の酸素が遮断された状態の食材中で菌が増殖し感染を起こす。	","	毒素が神経筋接合部でのアセチルコリンの放出を抑制し、弛緩性の麻痺を引き起こす。	","	毒素は熱に弱いため、食材の加熱により中毒を防ぐことができる。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	184	,question:"	破傷風およびその原因菌に関する説明として誤っているのはどれか。2つ選べ。	",	level:	3	,choices:["	痙攣性麻痺を引き起こす毒素としてテタノリジンを産生する。	","	光などの外来刺激により痙攣が誘発される。	","	土壌中の芽胞が組織に侵入して感染がおこる。	","	培養が容易であるため、診断は培養同定検査に基づいて行う。	","	破傷風トキソイドによる能動免疫により発病予防が可能である。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	185	,question:"	CTX-M型の基質特異性拡張型β-ラクタマーゼ（ESBL）では分解されないβラクタム系薬はどれか。2つ選べ。	",	level:	3	,choices:["	アズトレオナム（モノバクタム系薬）	","	セフトリアキソン（セファロスポリン系薬）	","	セフメタゾール（セファマイシン系薬）	","	ピペラシリン（ペニシリン系薬）	","	メロペネム（カルバペネム系薬）	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	186	,question:"	抗菌薬関連大腸炎の代表的な原因菌はどれか。2つ選べ。	",	level:	3	,choices:["	<em>Escherichia coli</em>	","	<em>Clostridioides difficile</em>	","	<em> Clostridium botulinum</em>	","	<em>Klebsiella oxytoca</em>	","	<em>Streptococcus agalactiae</em>	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	187	,question:"	感染症と聴取すべき病歴の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	オウム病　---　鳥類の飼育や鳥小屋の清掃	","	ツツガムシ病　---　海外渡航	","	夏型過敏性肺炎　---　抗菌薬の内服	","	破傷風　---　牛肉の生食	","	レジオネラ肺炎　---　温泉や24時間風呂での入浴	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	188	,question:"	抗ヘルペス薬として誤っているのはどれか。2つ選べ。	",	level:	3	,choices:["	アシクロビル	","	オセルタミビル	","	バラシクロビル	","	ファムシクロビル	","	リトナビル	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	189	,question:"	梅毒の診断に関する次の記述のうち正しいものはどれか。2つ選べ。	",	level:	3	,choices:["	TPHAは治療判定には不向きである。	","	TPHAは感染の早期から陽性となりやすい。	","	STSはカルジオリピンの血中濃度を測定する方法である。	","	STSでは自己免疫性疾患や妊娠が生物学的偽陽性の原因となりやすい。	","	TPHAは梅毒トレポネーマ由来成分の血中濃度を測定する方法である。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	190	,question:"	 ワクチンにより予防可能なウイルス感染症はどれか。2つ選べ。	",	level:	3	,choices:["	風疹	","	B型肝炎	","	C型肝炎	","	咽頭結膜熱	","	口唇ヘルペス	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	191	,question:"	<em>Chlamydia trachomatis</em>による尿道炎に対する抗菌薬として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	アジスロマイシン	","	アミカシン	","	ペニシリンG	","	ミノサイクリン	","	レボフロキサシン	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	192	,question:"	百日せきに関する説明として正しいのはどれか。	",	level:	3	,choices:["	2類感染症である。	","	抗菌薬が無効である。	","	感染症法で就業制限がある。	","	ワクチンにより予防可能な疾患である。	","	基本再生産数はインフルエンザよりも小さい。	"],	correct:[				"d",		],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	193	,question:"	梅毒の症状として<b><u>誤っている</u></b>のはどれか。	",	level:	3	,choices:["	脊髄癆	","	硬性下疳	","	尖圭コンジローマ	","	バラ疹	","	無痛性横痃	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	194	,question:"	原虫が<b><u>持たない</u></b>構造はどれか。	",	level:	3	,choices:["	核膜	","	細胞膜	","	細胞壁	","	ゴルジ体	","	ミトコンドリア	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	195	,question:"	疾患と病原体の組み合わせのうち正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	赤痢　---　<em>Candida albicans</em>	","	鵞口瘡　---　<em>Cryptococcus neoformans</em>	","	ムーコル症　---　<em>Rhizopus oryzae</em>	","	夏型過敏性肺炎　---　<em>Trichosporon asahii</em>	","	ニューモシスチス肺炎　---　<em>Aspergillus fumigatus</em>	"],	correct:[			"c",	"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	196	,question:"	カンジダ症およびその原因病原体について正しい説明はどれか。	",	level:	3	,choices:["	病型としては、肺感染症が最も多い。	","	原因としては,em>Candida albicans</em>が最も多い。	","	<em>Candida albicans</em>は細胞壁の周囲に莢膜を有する。	","	カンジダ血症では血清ガラクトマンナン抗原が陽性となる。	","	<em>Candida glabrata</em>にはキャンディン系抗真菌薬が無効である。	"],	correct:[		"b",				],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	197	,question:"	不活化ワクチンはどれか。	",	level:	3	,choices:["	MRワクチン	","	水痘ワクチン	","	日本脳炎ワクチン	","	ムンプスワクチン	","	ロタウイルスワクチン	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	198	,question:"	COVID-19ワクチンの接種経路として適切なのはどれか。	",	level:	3	,choices:["	皮内	","	皮下	","	経口	","	筋肉内	","	静脈内	"],	correct:[				"d",		],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	199	,question:"	ワクチンの筋肉注射について正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	接種後はしっかりと揉んでもらう。	","	不活化ワクチンの接種部位としては適さない。	","	成人では三角筋が接種部位として最も適している。	","	注入前には必ずシリンジを引いて血液の逆流を確認する。	","	接種時、被接種者は手を腰に当てず、腕を下ろした方がよい。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	200	,question:"	 感染症法の類型分類について正しい説明はどれか。	",	level:	3	,choices:["	一類は全てウイルス感染症である。	","	二類は全て節足動物媒介性である。	","	三類は全て細菌感染症である。	","	四類は全て呼吸器系の感染症である。	","	五類は全て全数把握の対象である。	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	201	,question:"	アデノウイルスによって起こる疾患はどれか。2つ選べ。	",	level:	3	,choices:["	手足口病	","	咽頭結膜熱	","	出血性結膜炎	","	ヘルパンギーナ	","	流行性角結膜炎	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	202	,question:"	PCRに必要な試薬・機器として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	Mg<sip>2+</sup>	","	EDTA	","	dNTP	","	TEバッファー	","	サーマルサイクラー	"],	correct:[		"b",		"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	203	,question:"	サンプルa, b, cに関して、リアルタイムPCRによる定量を実施した。基準物質のCt値が25、a, b, cのCtはそれぞれ22, 26, 32であった。添加したサンプルの初期量について正しい説明はどれか。	",	level:	3	,choices:["	aは基準物質の約1/8倍である。	","	bは基準物質の約1.2倍である。	","	cは基準物質の1000倍以上である。	","	aはbの約16倍である。	","	cはbの約1000倍である。	"],	correct:[				"d",		],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	204	,question:"	PCRで2つのプライマーのTm値がともに60℃の時、適切なアニーリング温度はどれか。	",	level:	3	,choices:["	12℃	","	36℃	","	57℃	","	65℃	","	82℃	"],	correct:[			"c",			],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	205	,question:"	PCRについて正しいのはどれか。	",	level:	3	,choices:["	変性温度は70℃付近に設定する。	","	プライマーのTm値は70℃付近に設定する。	","	Taqポリメラーゼの至適反応温度は37℃である。	","	アニーリングの温度はTm値よりも10℃高い温度とする。	","	アニーリング温度が低いほど非特異的な増幅が起こりやすい。	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	206	,question:"	PCRについて正しいのはどれか。	",	level:	3	,choices:["	定量的PCRでは蛍光物質を用いる。	","	定量的PCRではRNAを鋳型として用いる。	","	逆転写PCRではDNAポリメラーゼを用いない。	","	逆転写PCRではPCRの前にcDNAからmRNAを合成する。	","	マルチプレックスPCRでは二種類以上のDNAポリメラーゼを用いる。	"],	correct:[	"a",					],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	207	,question:"	PCRで適切なアニーリング温度 (Ta) について正しいのはどれか。	",	level:	3	,choices:["	常に50℃に設定する。	","	伸長温度よりも約2-3℃高く設定する。	","	増幅するDNA断片の長さを考慮して設定する。	","	変性温度よりも約5-10℃高い温度に設定する。	","	プライマーのTm値よりも約3-5℃低い温度に設定する。	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	208	,question:"	Taqポリメラーゼの至適温度について正しいのはどれか。	",	level:	3	,choices:["	25℃	","	37℃	","	50℃	","	60℃	","	72℃	"],	correct:[					"e",	],explanation:"	解説なし	",	selectionCount:	1	},		
{id:	209	,question:"	逆転写PCRについて正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	PCRの後に逆転写を行う。	","	六種類のプライマーを用いる。	","	cDNAを合成したのち、RNaseHでmRNAを分解する。	","	ミトコンドリア由来のDNAポリメラーゼγを用いる。	","	リアルタイムPCRと組み合わせることで、転写量の評価が可能である。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	210	,question:"	 肝炎ウイルスに関して正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	A型肝炎ウイルスはピコルナウイルス科に属する。	","	B型肝炎ウイルスはDNAウイルスである。	","	C型肝炎ウイルスは宿主のゲノムDNAに挿入される。	","	D型肝炎ウイルスは原核細胞に寄生する。	","	E型肝炎ウイルスはエンベロープを有する。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	211	,question:"	ウイルスに関して正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	黄熱ウイルスはトガウイルス科に属する。	","	ヘルペスウイルスはエンベロープを持たない。	","	パルボウイルスB19は一本鎖DNAウイルスである。	","	インフルエンザウイルスはモノネガウイルス目に属する。	","	伝染性軟属腫の原因ウイルスはポックスウイルス科に属する。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	212	,question:"	ポックスウイルスに関して正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	ポックスウイルスはエーテルに耐性がある。	","	水痘はポックスウイルスによって引き起こされる。	","	ポックスウイルスは複製のために核に入る必要がある。	","	ポックスウイルスはエンベロープを持たないウイルスである。	","	ポックスウイルスは最も大きく、最も複雑なDNAウイルスの一つである。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	213	,question:"	遺伝子に関して正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	TGAはストップをコードする。	","	ATGはメチオニンをコードする。	","	真核生物はポリシストロニックである。	","	シャイン-ダルガノ配列は+30に位置する。	","	岡崎フラグメントは相補的DNA（cDNA）である。	"],	correct:[	"a",	"b",				],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	214	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	レトロウイルスは宿主DNAに挿入される。	","	ポリオウイルスはDNAポリメラーゼを持つ。	","	インフルエンザウイルスは転写によってATPを得る。	","	ほとんどのコドンは2つ以上のアミノ酸をコードする。	","	ほとんどのアミノ酸は2つ以上のコドンによってコードされる。	"],	correct:[	"a",				"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	215	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	逆転写酵素はRNAテンプレートからDNAを合成する。	","	転移RNA（tRNA）はpre-mRNAのスプライシングに関与する。	","	メッセンジャーRNA（mRNA）はリボソームで蛋白質に翻訳される。	","	RNA依存性RNAポリメラーゼはDNAテンプレートからRNAを合成する。	","	リボソームRNA（rRNA）はタンパク質合成のテンプレートとして機能する。	"],	correct:[	"a",		"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	216	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	発酵には酸素が必要である。	","	クレブス回路は嫌気的条件で行われる。	","	ATPは細胞の主要なエネルギー通貨である。	","	細菌の解糖系はペリプラズム内で行われる。	","	偏性嫌気性菌は発酵によってエネルギーを得る。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	217	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	DNAは3'側から5'側に合成される。	","	アンチセンスはcDNAと同義である。	","	アンビセンスはアンチセンスと同義である。	","	一本鎖プラスRNA（ssRNA+）はmRNAに相当する。	","	一本鎖マイナスRNA（ssRNA-）はRNA依存性RNAポリメラーゼを必要とする。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	218	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	翻訳は細胞の核で行われる。	","	リボソームはmRNA合成の場である。	","	DNA複製は細胞周期のS期に行われる。	","	有糸分裂は4つの娘細胞の形成をもたらす。	","	転写はDNAテンプレートからmRNAを合成する過程である。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	219	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	代謝は異化作用と発酵を指す。	","	同化作用には酸素が必要である。	","	異化作用は消費するよりも多くのATPを生成する。	","	偏性嫌気性菌は呼吸によってのみエネルギーを得る。	","	異化作用は大きな分子を小さな分子に分解することを指す。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	220	,question:"	発熱性好中球減少症で特に考慮すべき感染症はどれか。2つ選べ。	",	level:	3	,choices:["	肺結核	","	カンジダ血症	","	伝染性単核症	","	サイトメガロウイルス肺炎	","	侵襲性肺アスペルギルス症	"],	correct:[		"b",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	221	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	生ワクチンは病原性の高い株を使用する。	","	ワクチンは受動免疫を提供することで機能する。	","	集団免疫は免疫を持っていない個人も保護する。	","	ブースターとはワクチンの効果が弱まる現象である。	","	ワクチンのアジュバントとして水酸化アルミニウムが知られている。	"],	correct:[		"c",			"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	222	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	グラム陽性菌は外膜を持つ。	","	芽胞は細菌が活発に増殖している形態である。	","	抗酸菌染色は<em>Mycobacterium</em>属の検出に使用される。	","	<em>Mycobacterium tuberculosis</em>はグラム陰性菌である。	","	グラム陽性菌はグラム陰性菌よりも厚いペプチドグリカン層を持つ。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	223	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	赤芽球は有核細胞である。	","	リンパ球は主に脾臓で産生される。	","	成人の造血は主に肝臓で行われる。	","	播種性血管内凝固症候群では血小板減少が起こる。	","	 G-CSFはリンパ球の造血を促すサイトカインである。	"],	correct:[	"a",			"d",		],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	224	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	オセルタミビルはDNAポリメラーゼを阻害する。	","	D4T（スタブジン）はHIVのプロテアーゼを阻害する。	","	ホスカルネットはウイルスのDNAポリメラーゼを阻害し、DNA複製を阻害する。	","	ソホスブビルはC型肝炎ウイルス（HCV）感染症の治療に使用される非ヌクレオチドポリメラーゼ阻害剤である。	","	 バロキサビルマルボキシルはインフルエンザウイルスポリメラーゼのキャップ依存性エンドヌクレアーゼ活性を阻害する。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	225	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	ストップコドンはスレオニンをコードする。	","	スタートコドンはメチオニンをコードする。	","	一つのコドンは3つのヌクレオチドで構成される。	","	すべてのコドンはアミノ酸と1対1で対応している。	","	 コドンでコードされるアミノ酸の種類は30種類である。	"],	correct:[		"b",	"c",			],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	226	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	mRNAはcDNAから合成される。	","	tRNAは特定のアミノ酸を運搬する。	","	mRNAはファゴソームで分解される。	","	rRNAは異なる菌種間でも同一である。	","	 細菌のmRNAはキャップとポリAテールを持たない。	"],	correct:[		"b",			"3",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	227	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	人工呼吸器はECMOの一種である。	","	劇症感染症は遅発性の感染症を指す。	","	血圧計のカフは個人防護具の一つである。	","	潜伏期とは、発病前の期間であり、後で症状が現れることがある。	","	 eradicationとは、意図的な努力によって新たな症例が世界的に完全かつ恒久的にゼロになることを指す。	"],	correct:[				"d",	"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	228	,question:"	正しい説明はどれか。2つ選べ。	",	level:	3	,choices:["	一次予防は病気の早期発見と治療を含む。	","	日和見感染症は主に健康な人に発生する。	","	エンドトキシンはグラム陰性菌の外膜に由来する。	","	パンデミックは特定の地域に限られた疾病の発生を指す。	","	 潜伏期間とは、感染因子への暴露から症状が現れるまでの時間を指す。	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	229	,question:"	用語とその定義の組み合わせとして正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	プラスミド - 複数の遺伝子を一緒に調節するDNAの断片	","	エキソトキシン - グラム陰性菌の外膜に存在するリポ多糖またはリポオリゴ糖	","	シデロフォア - 環境から鉄を獲得するために細菌が産生する化合物	","	オペロン - 細菌の染色体とは独立して複製される小さな環状のDNA分子	","	 クオラムセンシング（QS） - 微生物が自らが産生する分子によって細胞集団密度を感知し、集団行動を変化させるための細胞間コミュニケーションのメカニズム	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		
{id:	230	,question:"	正常な血液生化学の所見はどれか。2つ選べ。	",	level:	3	,choices:["	Cr 5 mg/dL	","	AST 120 U/L	","	UN 15 mg/dL	","	Na 110 mEq/L	","	 T-Bil 0.8 mg/dL	"],	correct:[			"c",		"e",	],explanation:"	解説なし	",	selectionCount:	2	},		/*
{id:	231	,question:"	なし　同一問題あり	",	level:	2	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題1</strong>	",	selectionCount:	0	},	*/	/*
{id:	232	,question:"	なし　同一問題あり	",	level:	2	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題2</strong>	",	selectionCount:	0	},	*/	
{id:	233	,question:"	β溶血性の細菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Streptococcus pyogenes</em>	","	<em>Streptococcus salivarius</em>	","	<em>Streptococcus agalactiae</em>	","	<em>Streptococcus anginosus</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[	"a",		"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題3</strong>	",	selectionCount:	2	},		
{id:	234	,question:"	コアグラーゼ陽性の細菌はどれか。	",	level:	2	,choices:["	<em>Staphylococcus aureus</em>	","	<em>Staphylococcus epidermidis</em>	","	<em>Staphylococcus lugdunensis</em>	","	<em>Staphylococcus haemolyticus</em>	","	<em>Staphylococcus saprophyticus</em>	"],	correct:[	"a",					],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題4</strong>	",	selectionCount:	1	},		
{id:	235	,question:"	⾷中毒原因菌のうち、3類感染症の原因菌として<b><u>誤っている</u></b>のはどれか。2つ選べ。	",	level:	3	,choices:["	<em>Vibrio cholerae</em>	","	<em>Shigella sonnei</em>	","	<em>Yersinia enterocolitica</em>	","	<em>Salmonella</em> Typhimurium	","	Enterohemorrhagic <em>Escherichia coli</em>	"],	correct:[			"c",	"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題5</strong>	",	selectionCount:	2	},		
{id:	236	,question:"	Which of the following pathogens of pneumonia is the urinary antigen test available for diagnosis? Choose two.	",	level:	2	,choices:["	<em>Chlamydia psittaci</em>	","	<em>Mycobacterium avium</em>	","	<em>Legionella pneumophila</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[			"c",		"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題6</strong>	",	selectionCount:	2	},		
{id:	237	,question:"	Which of the following disease-pathogen combinations is correct? Choose two.	",	level:	4	,choices:["	Creutzfeldt-Jakob disease --- JC virus	","	Epidemic typhus --- <em>Salmonella</em> Typhi	","	Gas gangrene --- <em>Clostridium perfringens</em>	","	Amoebic dysentery --- <em>Acanthamoeba castellanii</em>	","	Lemierre syndrome --- <em>Fusobacterium necrophorum</em>	"],	correct:[			"c",		"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題7</strong>	",	selectionCount:	2	},		/*
{id:	238	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題8</strong>	",	selectionCount:	0	},	*/	/*
{id:	239	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題9</strong>	",	selectionCount:	0	},	*/	
{id:	240	,question:"	セファロスポリン系薬が<b><u>無効な</u></b>細菌はどれか。2つ選べ。	",	level:	4	,choices:["	<em>Acinetobacter baumannii</em>	","	<em>Enterococcus faecium</em>	","	<em>Escherichia coli</em>	","	<em>Listeria monocytogenes</em>	","	<em>Pseudomonas aeruginosa</em>	"],	correct:[		"b",		"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題10</strong>	",	selectionCount:	2	},		
{id:	241	,question:"	Which of the following diseases is caused by <em>Helicobacter pylori</em>? Choose two.	",	level:	4	,choices:["	Hard chancre	","	Hereditary spherocytosis	","	Immune thrombocytopenia	","	Barrett's esophageal cancer	","	Gastric mucosa-associated lymphoid tissue lymphomas	"],	correct:[			"c",		"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題11</strong>	",	selectionCount:	2	},		
{id:	242	,question:"	Which of the following infectious diseases can cause jaundice? Choose two.	",	level:	4	,choices:["	Rabies	","	Ascariasis	","	Yellow fever	","	Leptospirosis	","	Infectious mononucleosis	"],	correct:[			"c",	"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題12</strong>	",	selectionCount:	2	},		
{id:	243	,question:"	22歳の男性。咽頭痛と微熱を主訴に来院した。10日前から咽頭痛と37℃台の発熱があった。体温38.3℃。扁桃腫大は認めない。両頸部に径0.5 cmのリンパ節を2個ずつ触知するが疼痛や圧痛はない。肝臓および脾臓を肋骨弓下にそれぞれ1 cm触知する。 血液所⾒：白血球3,600（桿状核好中球3%、分葉核好中球16%、単球13%、リンパ球59%、異型リンパ球9%）。血液生化学所⾒： AST325 U/L、ALT 286 U/L。CRP6. 7 mg/dL。<br>最も考えられる疾患はどれか。（第115回医師国家試験D45より一部改変）	",	level:	4	,choices:["	Influenza A	","	Scarlet fever	","	Strongyloidiasis	","	Acute hepatitis E	","	Infectious mononucleosis	"],	correct:[					"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題13</strong>	",	selectionCount:	1	},		
{id:	244	,question:"	22歳の男性。咽頭痛と微熱を主訴に来院した。10日前から咽頭痛と37℃台の発熱があった。体温38.3℃。扁桃腫大は認めない。両頸部に径0.5 cmのリンパ節を2個ずつ触知するが疼痛や圧痛はない。肝臓および脾臓を肋骨弓下にそれぞれ1 cm触知する。 血液所⾒：白血球3,600（桿状核好中球3%、分葉核好中球16%、単球13%、リンパ球59%、異型リンパ球9%）。血液生化学所⾒： AST325 U/L、ALT 286 U/L。CRP6. 7 mg/dL。<br>適切な治療薬はどれか。（第115回医師国家試験D45より一部改変）	",	level:	4	,choices:["	Acyclovir	","	Ivermectin	","	Amoxicillin	","	Oseltamivir	","	Acetaminophen	"],	correct:[					"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題14</strong>	",	selectionCount:	1	},		
{id:	245	,question:"	Which of the following diseases is associated with axillary lymphadenopathy?	",	level:	3	,choices:["	Rabies	","	Mumps	","	Varicella	","	Cat scratch disease	","	Lymphogranuloma venereum	"],	correct:[				"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題15</strong>	",	selectionCount:	1	},		
{id:	246	,question:"	Which of the following explanations are compatible with non-tuberculous mycobacteria infection caused by <em>Mycobacterium avium</em> complex? Choose two.	",	level:	3	,choices:["	It predominantly affects middle-aged women.	","	Gimenez staining of sputum is useful for diagnosis.	","	IGRA (Interferon Gamma Release Assay) tests positive.	","	It predominantly affects the S4 and S5 segments of the lung.	","	Nucleic acid testing of sputum does not differentiate it from tuberculosis.	"],	correct:[	"a",			"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題16</strong>	",	selectionCount:	2	},		
{id:	247	,question:"	バンコマイシン耐性腸球菌のバンコマイシン耐性機構はどれか。	",	level:	5	,choices:["	排出ポンプ	","	分解酵素の産生	","	外膜の透過性の変化	","	変異型細胞壁合成酵素PBP2’の産生	","	細胞壁成分D-Ala-D-AlaのD-Ala-D-Lacへの変化	"],	correct:[					"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題17</strong>	",	selectionCount:	1	},		
{id:	248	,question:"	de-escalationはどれか。2つ選べ。	",	level:	3	,choices:["	アンピシリンをセファゾリンに変更する。	","	バンコマイシンをセファゾリンに変更する。	","	メロペネムをセフトリアキソンに変更する。	","	セフトリアキソンを1日4回から1日2回に減らす。	","	メロペネムの1回投与量を1 gから0.5 gに減量する。	"],	correct:[		"b",	"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題18</strong>	",	selectionCount:	2	},		/*
{id:	249	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題19</strong>	",	selectionCount:	0	},	*/	/*
{id:	250	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題20</strong>	",	selectionCount:	0	},	*/	/*
{id:	251	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題21</strong>	",	selectionCount:	0	},	*/	
{id:	252	,question:"	57歳の男性。左耳痛を主訴に来院した。昨日から左耳痛があり、今朝から左側の顔が動きにくく、左眼が閉じられなくなったため受診した。左耳介に紅斑と水疱の形成を認める。左側の顔面麻痺を認める。最も考えられる疾患はどれか。（第117回医師国家試験A27より一部改変）	",	level:	4	,choices:["	Mumps	","	Skarlet fever	","	Lemierre’s syndrome	","	Ramsay-Hunt syndrome	","	Infectious mononucleosis	"],	correct:[				"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題22</strong>	",	selectionCount:	1	},		
{id:	253	,question:"	57歳の男性。左耳痛を主訴に来院した。昨日から左耳痛があり、今朝から左側の顔が動きにくく、左眼が閉じられなくなったため受診した。左耳介に紅斑と水疱の形成を認める。左側の顔面麻痺を認める。原因として最も可能性が⾼い病原体はどれか。（第117回医師国家試験A27より一部改変）	",	level:	4	,choices:["	Adenovirus	","	Mumps virus	","	Coxsackievirus	","	Varicella-zoster virus	","	<em>Streptococcus pyogenes</em>	"],	correct:[				"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題23</strong>	",	selectionCount:	1	},		
{id:	254	,question:"	真菌症について正しい説明はどれか。2つ選べ。	",	level:	4	,choices:["	肺結核後遺症は慢性肺アスペルギルス症の基礎疾患である。	","	夏型過敏性肺炎は播種性トリコスポロン症の危険因子である。	","	カンジダ血症の基礎疾患として後天性免疫不全症候群が最も多い。	","	侵襲性肺ムーコル症の診断には血清ガラクトマンナン抗原が有用である。	","	肺クリプトコックス症の診断には血清グルクロノキシロマンナン抗原が有用である。	"],	correct:[	"a",				"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題24</strong>	",	selectionCount:	2	},		
{id:	255	,question:"	腸内細菌科細菌に分類される細菌はどれか。2つ選べ。	",	level:	2	,choices:["	<em>Escherichia coli</em>	","	<em>Enterococcus faecium</em>	","	<em>Klebsiella pneumoniae</em>	","	<em>Acinetobacter baumannii</em>	","	<em>Pseudomonas aeruginosa</em>	"],	correct:[	"a",		"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題25</strong>	",	selectionCount:	2	},		
{id:	256	,question:"	髄膜炎の鑑別において、ウイルス性よりも細菌性を強く疑う所⾒として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	項部硬直	","	体温 38度	","	髄液中の糖 8 mg/dL	","	jolt accentuation陽性	","	好中球優位の髄液中細胞数増加	"],	correct:[			"c",		"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題26</strong>	",	selectionCount:	2	},		
{id:	257	,question:"	糞便の塗抹染色を行って感染性下痢症の原因菌の診断が可能な菌はどれか。	",	level:	3	,choices:["	<em>Shigella sonnei</em>	","	<em>Anisakis simplex</em>	","	<em>Salmonella</em> Typhi	","	<em>Camplylobacter jejuni</em>/<em>coli</em>	","	enterohaemorrhagic <em>Escherichia coli</em>	"],	correct:[				"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題27</strong>	",	selectionCount:	1	},		
{id:	258	,question:"	Which of the following descriptions accurately represents a symptom of Lemierre's syndrome?	",	level:	5	,choices:["	Septic thrombophlebitis of the internal jugular vein	","	Sudden loss of vision in one eye and oculomotor dysfunction	","	Rapidly progressing acute gangrenous infection of the anorectal and urogenital area	","	A progressive and symmetric muscle weakness of limbs and absent or depressed deep tendon reflexes	","	Complication of pelvic inflammatory disease, most commonly resulting from infections caused by <em>Chlamydia trachomatis</em> or <em>Neisseria gonorrhoeae</em>	"],	correct:[	"a",					],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題28</strong>	",	selectionCount:	1	},		
{id:	259	,question:"	ピロリ菌感染症の一次除菌に用いる薬剤はどれか。2つ選べ。	",	level:	3	,choices:["	クラリスロマイシン	","	ピペラシリン	","	シメチジン	","	ランソプラゾール	","	バンコマイシン	"],	correct:[	"a",			"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題29</strong>	",	selectionCount:	2	},		
{id:	260	,question:"	Which of the following statements is correct regarding latent tuberculosis infection (LTBI)? Choose two.	",	level:	3	,choices:["	LTBI is characterized by active, symptomatic tuberculosis that can spread to others.	","	People with LTBI do not show symptoms, and cannot spread tuberculosis to others.	","	Treatment for LTBI is not necessary because it cannot develop into active tuberculosis.	","	LTBI can only be diagnosed through a physical examination showing typical symptoms of tuberculosis.	","	LTBI can progress to active tuberculosis, especially in individuals with weakened immune systems.	"],	correct:[		"b",			"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題30</strong>	",	selectionCount:	2	},		
{id:	261	,question:"	潜在性結核感染症（LTBI）の治療について正しいのはどれか。2つ選べ。	",	level:	4	,choices:["	イソニアジド単剤で6か月治療	","	デラマニドとベダキリンの併用で12か月治療	","	イソニアジドとリファンピシンの併用で4か月治療	","	イソニアジド、リファンピシン、エタンブトール、3剤で9か月治療	","	イソニアジド、リファンピシン、エタンブトール、ピラジナマイドの4剤で6か月治療	"],	correct:[	"a",		"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題31</strong>	",	selectionCount:	2	},		
{id:	262	,question:"	口腔カンジダ症の基礎疾患または危険因子として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	BCG接種歴	","	ステロイドの内服	","	後天性免疫不全症候群	","	フルコナゾールの内服	","	CD4陽性細胞が400/μL以上	"],	correct:[		"b",	"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題32</strong>	",	selectionCount:	2	},		
{id:	263	,question:"	Which of the following drugs are triazole antifungal agents? Choose two.	",	level:	3	,choices:["	Fluconazole	","	Omeprazole	","	Voriconazole	","	Lansoprazole	","	Metronidazole	"],	correct:[	"a",		"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題33</strong>	",	selectionCount:	2	},		
{id:	264	,question:"	Which of the following are nucleic acid amplification tests (NAT)? Choose two.	",	level:	2	,choices:["	Western blotting	","	Radioallergosorbent test	","	Polymerase chain reaction	","	Enzyme-linked immuno sorbent assay	","	Loop-mediated isothermal amplification	"],	correct:[			"c",		"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題34</strong>	",	selectionCount:	2	},		
{id:	265	,question:"	B細胞に対する生物学的製剤はどれか。	",	level:	3	,choices:["	ニボルマブ	","	リツキシマブ	","	ゲフィチニブ	","	レノグラスチム	","	ベズロトクスマブ	"],	correct:[		"b",				],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題35</strong>	",	selectionCount:	1	},		
{id:	266	,question:"	Which of the following organisms are the most likely causative agents if a blood culture is positive only in the aerobic bottle? Choose two.	",	level:	2	,choices:["	<em>Escherichia coli</em>	","	<em>Bacteroides fragilis</em>	","	<em>Staphylococcus aureus</em>	","	<em>Pseudomonas aeruginosa</em>	","	<em>Acinetobacter baumannii</em>	"],	correct:[				"d",	"e",	],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題36</strong>	",	selectionCount:	2	},		
{id:	267	,question:"	Which of the following is the target molecule of lansoprazole?	",	level:	2	,choices:["	Pepsin	","	Proteinase K	","	H<sup>+</sup>/K<sup>+</sup> ATPase	","	M3 muscarinic receptor	","	Histamine H2 receptor	"],	correct:[			"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題37</strong>	",	selectionCount:	1	},		
{id:	268	,question:"	疾患に関する説明として正しいのはどれか。2つ選べ。	",	level:	3	,choices:["	腸チフスでは比較的徐脈が⾒られる。	","	妊婦のジカ熱では胎児の小頭症が⾒られる。	","	日本脳炎は日本固有の蚊による感染症である。	","	ギラン-バレー症候群は遅発性ウイルス感染症である。	","	三日熱マラリアは約72時間おきに発熱が繰り返される。	"],	correct:[	"a",	"b",				],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題38</strong>	",	selectionCount:	2	},		/*
{id:	269	,question:"	なし　同一問題あり	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題39</strong>	",	selectionCount:	0	},	*/	/*
{id:	270	,question:"	なし　同一問題あり	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題40</strong>	",	selectionCount:	0	},	*/	
{id:	271	,question:"	50代の男性。発熱と咳嗽とを主訴に来院した。1週前に温泉に行ったという。意識は清明。体温38.5℃。脈拍96/分、整。血圧142/84mmHg。呼吸数30/分。SpO<sub>2</sub> 93％（リザーバー付マスク10L/分酸素投与下）。胸部エックス線写真にて右中下肺野に浸潤影を認め、喀痰のヒメネス〈Gimenez〉染色標本で桿菌を認めた。原因菌として最も考えられるのはどれか。（第108回医師国家試験D55より抜粋改変）	",	level:	3	,choices:["	<em>Staphylococcus aureus</em>	","	<em>Haemophilus influenzae</em>	","	<em>Legionella pneumophila</em>	","	<em>Mycoplasma pneumoniae</em>	","	<em>Streptococcus pneumoniae</em>	"],	correct:[			"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題41</strong>	",	selectionCount:	1	},		
{id:	272	,question:"	50代の男性。発熱と咳嗽とを主訴に来院した。1週前に温泉に行ったという。意識は清明。体温38.5℃。脈拍96/分、整。血圧142/84mmHg。呼吸数30/分。SpO<sub>2</sub> 93％（リザーバー付マスク10L/分酸素投与下）。胸部エックス線写真にて右中下肺野に浸潤影を認め、喀痰のヒメネス〈Gimenez〉染色標本で桿菌を認めた。動脈血ガス分析の結果は、次の通りであった。<br>PaO<sub>2</sub> 75 Torr、PaCO<sub>2</sub> 36 Torr、pH 7.48<br>A-aDO<sub>2</sub>を計算しなさい。ただし、大気圧は760 Torr、飽和水蒸気圧は47 Torr、FIO<sub>2</sub>=1.0とする。（第108回医師国家試験D55より抜粋改変）	",	level:	4	,choices:["	34	","	328	","	593	","	658	","	判定できない	"],	correct:[			"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題42</strong>	",	selectionCount:	1	},		
{id:	273	,question:"	50代の男性。発熱と咳嗽とを主訴に来院した。1週前に温泉に行ったという。意識は清明。体温38.5℃。脈拍96/分、整。血圧142/84mmHg。呼吸数30/分。SpO<sub>2</sub> 93％（リザーバー付マスク10L/分酸素投与下）。胸部エックス線写真にて右中下肺野に浸潤影を認め、喀痰のヒメネス〈Gimenez〉染色標本で桿菌を認めた。抗菌薬として適切なのはどれか。2つ選べ。（第108回医師国家試験D55より抜粋改変）	",	level:	3	,choices:["	アジスロマイシン	","	アンピシリン/スルバクタム	","	シプロフロキサシン	","	バンコマイシン	","	メロペネム	"],	correct:[	"a",		"c",			],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題43</strong>	",	selectionCount:	2	},		
{id:	274	,question:"	鼻咽頭部の味覚を支配する神経はどれか。	",	level:	3	,choices:["	鼓索神経	","	舌咽神経	","	舌下神経	","	迷走神経	","	大錐体神経	"],	correct:[				"d",		],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題44</strong>	",	selectionCount:	1	},		
{id:	275	,question:"	成人の三角筋での筋⾁注射で、注射部位が遠位側にずれると損傷する可能性の⾼い神経はどれか。（第117回医師国家試験E9より一部改変）	",	level:	2	,choices:["	腋窩神経	","	橈骨神経	","	尺骨神経	","	腓骨神経	","	脛骨神経	"],	correct:[		"b",				],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題45</strong>	",	selectionCount:	1	},		/*
{id:	276	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題46</strong>	",	selectionCount:	0	},	*/	/*
{id:	277	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題47</strong>	",	selectionCount:	0	},	*/	/*
{id:	278	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題48</strong>	",	selectionCount:	0	},	*/	/*
{id:	279	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題49</strong>	",	selectionCount:	0	},	*/	/*
{id:	280	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題50</strong>	",	selectionCount:	0	},	*/	/*
{id:	281	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題51</strong>	",	selectionCount:	0	},	*/	/*
{id:	282	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題52</strong>	",	selectionCount:	0	},	*/	/*
{id:	283	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題53</strong>	",	selectionCount:	0	},	*/	/*
{id:	284	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題54</strong>	",	selectionCount:	0	},	*/	/*
{id:	285	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題55</strong>	",	selectionCount:	0	},	*/	/*
{id:	286	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題56</strong>	",	selectionCount:	0	},	*/	/*
{id:	287	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題57</strong>	",	selectionCount:	0	},	*/	/*
{id:	288	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題58</strong>	",	selectionCount:	0	},	*/	/*
{id:	289	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題59</strong>	",	selectionCount:	0	},	*/	/*
{id:	290	,question:"	なし	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	<span class='kakomon'>感統</span>2024本試験-<strong>問題60</strong>	",	selectionCount:	0	},	*/	/*
{id:	291	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	292	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	293	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	294	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	295	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/	/*
{id:	0	,question:"	0	",	level:	0	,choices:["	0	","	0	","	0	","	0	","	0	"],	correct:[						],explanation:"	0	",	selectionCount:	0	},	*/
];


//問題の作成方法
/*    {
    id: 1,
    question: "グラム陽性ブドウ状球菌はどれか。",
    level: 1,
    choices: ["<i>Escherichia coli</i>", "<i>Staphylococcus aureus</i>", "<i>Streptococcus pneumoniae</i>", "<i>Klebsiella pneumoniae</i>", "<i>Mycoplasma pneumoniae</i>"],
    correct: ["b"],
    explanation: "<i>Staphylococcus aureus</i>は黄色ブドウ球菌。<i>Staphylococcus</i>（ブドウ球菌）属は、グラム陽性でcluster状の形態を示す。",
    selectionCount: 1 // 単一選択
},
{
    id: 2,
    question: "グラム陽性球菌はどれか。2つ選べ。",
    level: 1,
    choices: ["<i>Staphylococcus aureus</i>", "<i>Escherichia coli</i>", "<i>Streptococcus pneumoniae</i>", "<i>Klebsiella pneumoniae</i>", "<i>Pseudomonas aeruginosa</i>"],
    correct: ["a", "c"],
    explanation: "グラム陽性球菌は、連鎖状（chain）とブドウの房状（cluster）に分類される。<i>Streptococcus</i>（レンサ球菌）属と<i>Enterococcus</i>（腸球菌）属は代表的なchainを示すが、<i>Streptococcus pneumoniae</i>は双球菌である。<i>Staphylococcus</i>（ブドウ球菌）属は文字通りclusterを示す。",
    selectionCount: 2 // 複数選択（2つ選ぶ）
},
{
    id: 3,
    question: "以下の選択肢のうち、1つ以上選んでください。",
    level: 3,
    choices: ["選択肢1", "選択肢2", "選択肢3", "選択肢4", "選択肢5"],
    correct: ["a", "b", "c", "d", "e"],
    explanation: "すべてが正解として選択可能です。",
    selectionCount: "all" // 1つ以上選ぶ可能性がある
},
*/
